// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  Asm1CreateCalculationJobData,
  Asm1CreateCalculationJobResponse,
  Asm1CreateCalculationJobFromFlowchartData,
  Asm1CreateCalculationJobFromFlowchartResponse,
  Asm1GetCalculationResultSummaryData,
  Asm1GetCalculationResultSummaryResponse,
  Asm1GetCalculationFinalValuesData,
  Asm1GetCalculationFinalValuesResponse,
  Asm1GetCalculationTimeseriesData,
  Asm1GetCalculationTimeseriesResponse,
  Asm1GetCalculationStatusData,
  Asm1GetCalculationStatusResponse,
  Asm1ValidateCalculationInputData,
  Asm1ValidateCalculationInputResponse,
  Asm1GetUserCalculationJobsData,
  Asm1GetUserCalculationJobsResponse,
  Asm1DeleteCalculationJobData,
  Asm1DeleteCalculationJobResponse,
  Asm1GetJobInputDataData,
  Asm1GetJobInputDataResponse,
  Asm1FlowchartsReadAsm1FlowchartsData,
  Asm1FlowchartsReadAsm1FlowchartsResponse,
  Asm1FlowchartsCreateAsm1FlowchartData,
  Asm1FlowchartsCreateAsm1FlowchartResponse,
  Asm1FlowchartsReadAsm1FlowchartData,
  Asm1FlowchartsReadAsm1FlowchartResponse,
  Asm1FlowchartsUpdateAsm1FlowchartData,
  Asm1FlowchartsUpdateAsm1FlowchartResponse,
  Asm1FlowchartsDeleteAsm1FlowchartData,
  Asm1FlowchartsDeleteAsm1FlowchartResponse,
  Asm1SlimCreateCalculationJobData,
  Asm1SlimCreateCalculationJobResponse,
  Asm1SlimCreateCalculationJobFromFlowchartData,
  Asm1SlimCreateCalculationJobFromFlowchartResponse,
  Asm1SlimGetCalculationResultSummaryData,
  Asm1SlimGetCalculationResultSummaryResponse,
  Asm1SlimGetCalculationFinalValuesData,
  Asm1SlimGetCalculationFinalValuesResponse,
  Asm1SlimGetCalculationTimeseriesData,
  Asm1SlimGetCalculationTimeseriesResponse,
  Asm1SlimGetCalculationStatusData,
  Asm1SlimGetCalculationStatusResponse,
  Asm1SlimValidateCalculationInputData,
  Asm1SlimValidateCalculationInputResponse,
  Asm1SlimGetUserCalculationJobsData,
  Asm1SlimGetUserCalculationJobsResponse,
  Asm1SlimDeleteCalculationJobData,
  Asm1SlimDeleteCalculationJobResponse,
  Asm1SlimGetJobInputDataData,
  Asm1SlimGetJobInputDataResponse,
  Asm1SlimFlowchartsReadAsm1SlimFlowchartsData,
  Asm1SlimFlowchartsReadAsm1SlimFlowchartsResponse,
  Asm1SlimFlowchartsCreateAsm1SlimFlowchartData,
  Asm1SlimFlowchartsCreateAsm1SlimFlowchartResponse,
  Asm1SlimFlowchartsReadAsm1SlimFlowchartData,
  Asm1SlimFlowchartsReadAsm1SlimFlowchartResponse,
  Asm1SlimFlowchartsUpdateAsm1SlimFlowchartData,
  Asm1SlimFlowchartsUpdateAsm1SlimFlowchartResponse,
  Asm1SlimFlowchartsDeleteAsm1SlimFlowchartData,
  Asm1SlimFlowchartsDeleteAsm1SlimFlowchartResponse,
  Asm3CreateCalculationJobData,
  Asm3CreateCalculationJobResponse,
  Asm3CreateCalculationJobFromFlowchartData,
  Asm3CreateCalculationJobFromFlowchartResponse,
  Asm3GetCalculationResultSummaryData,
  Asm3GetCalculationResultSummaryResponse,
  Asm3GetCalculationFinalValuesData,
  Asm3GetCalculationFinalValuesResponse,
  Asm3GetCalculationTimeseriesData,
  Asm3GetCalculationTimeseriesResponse,
  Asm3GetCalculationStatusData,
  Asm3GetCalculationStatusResponse,
  Asm3ValidateCalculationInputData,
  Asm3ValidateCalculationInputResponse,
  Asm3GetUserCalculationJobsData,
  Asm3GetUserCalculationJobsResponse,
  Asm3DeleteCalculationJobData,
  Asm3DeleteCalculationJobResponse,
  Asm3GetJobInputDataData,
  Asm3GetJobInputDataResponse,
  Asm3FlowchartsReadAsm3FlowchartsData,
  Asm3FlowchartsReadAsm3FlowchartsResponse,
  Asm3FlowchartsCreateAsm3FlowchartData,
  Asm3FlowchartsCreateAsm3FlowchartResponse,
  Asm3FlowchartsReadAsm3FlowchartData,
  Asm3FlowchartsReadAsm3FlowchartResponse,
  Asm3FlowchartsUpdateAsm3FlowchartData,
  Asm3FlowchartsUpdateAsm3FlowchartResponse,
  Asm3FlowchartsDeleteAsm3FlowchartData,
  Asm3FlowchartsDeleteAsm3FlowchartResponse,
  FlowchartsReadFlowchartsData,
  FlowchartsReadFlowchartsResponse,
  FlowchartsCreateFlowchartData,
  FlowchartsCreateFlowchartResponse,
  FlowchartsReadFlowchartData,
  FlowchartsReadFlowchartResponse,
  FlowchartsUpdateFlowchartData,
  FlowchartsUpdateFlowchartResponse,
  FlowchartsDeleteFlowchartData,
  FlowchartsDeleteFlowchartResponse,
  ItemsReadItemsData,
  ItemsReadItemsResponse,
  ItemsCreateItemData,
  ItemsCreateItemResponse,
  ItemsReadItemData,
  ItemsReadItemResponse,
  ItemsUpdateItemData,
  ItemsUpdateItemResponse,
  ItemsDeleteItemData,
  ItemsDeleteItemResponse,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginTestTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentResponse,
  MaterialBalanceCreateCalculationJobData,
  MaterialBalanceCreateCalculationJobResponse,
  MaterialBalanceCreateCalculationJobFromFlowchartData,
  MaterialBalanceCreateCalculationJobFromFlowchartResponse,
  MaterialBalanceGetCalculationResultSummaryData,
  MaterialBalanceGetCalculationResultSummaryResponse,
  MaterialBalanceGetCalculationFinalValuesData,
  MaterialBalanceGetCalculationFinalValuesResponse,
  MaterialBalanceGetCalculationTimeseriesData,
  MaterialBalanceGetCalculationTimeseriesResponse,
  MaterialBalanceGetCalculationStatusData,
  MaterialBalanceGetCalculationStatusResponse,
  MaterialBalanceValidateCalculationInputData,
  MaterialBalanceValidateCalculationInputResponse,
  MaterialBalanceGetUserCalculationJobsData,
  MaterialBalanceGetUserCalculationJobsResponse,
  MaterialBalanceDeleteCalculationJobData,
  MaterialBalanceDeleteCalculationJobResponse,
  MaterialBalanceGetJobInputDataData,
  MaterialBalanceGetJobInputDataResponse,
  PrivateCreateUserData,
  PrivateCreateUserResponse,
  SimpleWebsocketGetTaskConnectionsData,
  SimpleWebsocketGetTaskConnectionsResponse,
  SimpleWebsocketBroadcastMessageData,
  SimpleWebsocketBroadcastMessageResponse,
  SimpleWebsocketWebsocketHealthResponse,
  StatsGetDashboardStatsResponse,
  StatsGetUserStatsResponse,
  UdmCreateCalculationJobData,
  UdmCreateCalculationJobResponse,
  UdmCreateCalculationJobFromFlowchartData,
  UdmCreateCalculationJobFromFlowchartResponse,
  UdmGetCalculationResultSummaryData,
  UdmGetCalculationResultSummaryResponse,
  UdmGetCalculationFinalValuesData,
  UdmGetCalculationFinalValuesResponse,
  UdmGetCalculationTimeseriesData,
  UdmGetCalculationTimeseriesResponse,
  UdmGetCalculationStatusData,
  UdmGetCalculationStatusResponse,
  UdmValidateCalculationInputData,
  UdmValidateCalculationInputResponse,
  UdmGetUserCalculationJobsData,
  UdmGetUserCalculationJobsResponse,
  UdmDeleteCalculationJobData,
  UdmDeleteCalculationJobResponse,
  UdmGetJobInputDataData,
  UdmGetJobInputDataResponse,
  UdmFlowchartsReadUdmFlowchartsData,
  UdmFlowchartsReadUdmFlowchartsResponse,
  UdmFlowchartsCreateUdmFlowchartData,
  UdmFlowchartsCreateUdmFlowchartResponse,
  UdmFlowchartsReadUdmFlowchartData,
  UdmFlowchartsReadUdmFlowchartResponse,
  UdmFlowchartsUpdateUdmFlowchartData,
  UdmFlowchartsUpdateUdmFlowchartResponse,
  UdmFlowchartsDeleteUdmFlowchartData,
  UdmFlowchartsDeleteUdmFlowchartResponse,
  UdmModelsGetUdmTemplatesResponse,
  UdmModelsValidateUdmModelDefinitionData,
  UdmModelsValidateUdmModelDefinitionResponse,
  UdmModelsCreateUdmModelData,
  UdmModelsCreateUdmModelResponse,
  UdmModelsReadUdmModelsData,
  UdmModelsReadUdmModelsResponse,
  UdmModelsCreateUdmModelFromTemplateData,
  UdmModelsCreateUdmModelFromTemplateResponse,
  UdmModelsReadUdmModelData,
  UdmModelsReadUdmModelResponse,
  UdmModelsUpdateUdmModelData,
  UdmModelsUpdateUdmModelResponse,
  UdmModelsDeleteUdmModelData,
  UdmModelsDeleteUdmModelResponse,
  UsersReadUsersData,
  UsersReadUsersResponse,
  UsersCreateUserData,
  UsersCreateUserResponse,
  UsersReadUserMeResponse,
  UsersDeleteUserMeResponse,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeResponse,
  UsersRegisterUserData,
  UsersRegisterUserResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdResponse,
  UsersUpdateUserData,
  UsersUpdateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserResponse,
  UtilsTestEmailData,
  UtilsTestEmailResponse,
  UtilsHealthCheckResponse,
} from "./types.gen"

export class Asm1Service {
  /**
   * Create Calculation Job
   * 创建ASM1计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM1JobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJob(
    data: Asm1CreateCalculationJobData,
  ): CancelablePromise<Asm1CreateCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1/calculate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Calculation Job From Flowchart
   * 从流程图数据创建ASM1计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM1JobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJobFromFlowchart(
    data: Asm1CreateCalculationJobFromFlowchartData,
  ): CancelablePromise<Asm1CreateCalculationJobFromFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1/calculate-from-flowchart",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Result Summary
   * 获取ASM1计算结果摘要
   * @param data The data for the request.
   * @param data.jobId
   * @returns MaterialBalanceResultSummary Successful Response
   * @throws ApiError
   */
  public static getCalculationResultSummary(
    data: Asm1GetCalculationResultSummaryData,
  ): CancelablePromise<Asm1GetCalculationResultSummaryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1/result/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Final Values
   * 获取ASM1计算的最终值
   * @param data The data for the request.
   * @param data.jobId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getCalculationFinalValues(
    data: Asm1GetCalculationFinalValuesData,
  ): CancelablePromise<Asm1GetCalculationFinalValuesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1/result/{job_id}/final-values",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Timeseries
   * 获取ASM1计算的时间序列数据
   * @param data The data for the request.
   * @param data.jobId
   * @param data.startTime 开始时间 (小时)
   * @param data.endTime 结束时间 (小时)
   * @param data.page 页码
   * @param data.pageSize 每页数据量
   * @param data.nodeIds 指定节点ID列表
   * @param data.edgeIds 指定边ID列表
   * @returns MaterialBalanceTimeSeriesResponse Successful Response
   * @throws ApiError
   */
  public static getCalculationTimeseries(
    data: Asm1GetCalculationTimeseriesData,
  ): CancelablePromise<Asm1GetCalculationTimeseriesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1/result/{job_id}/timeseries",
      path: {
        job_id: data.jobId,
      },
      query: {
        start_time: data.startTime,
        end_time: data.endTime,
        page: data.page,
        page_size: data.pageSize,
        node_ids: data.nodeIds,
        edge_ids: data.edgeIds,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Status
   * 获取ASM1计算任务状态
   * @param data The data for the request.
   * @param data.jobId
   * @returns ASM1JobPublic Successful Response
   * @throws ApiError
   */
  public static getCalculationStatus(
    data: Asm1GetCalculationStatusData,
  ): CancelablePromise<Asm1GetCalculationStatusResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1/status/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Validate Calculation Input
   * 验证ASM1计算输入数据
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MaterialBalanceValidationResponse Successful Response
   * @throws ApiError
   */
  public static validateCalculationInput(
    data: Asm1ValidateCalculationInputData,
  ): CancelablePromise<Asm1ValidateCalculationInputResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1/validate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Calculation Jobs
   * 获取用户的ASM1计算任务列表
   * @param data The data for the request.
   * @param data.skip 跳过的记录数
   * @param data.limit 返回的记录数
   * @returns ASM1JobsPublic Successful Response
   * @throws ApiError
   */
  public static getUserCalculationJobs(
    data: Asm1GetUserCalculationJobsData = {},
  ): CancelablePromise<Asm1GetUserCalculationJobsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1/jobs",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Calculation Job
   * 删除ASM1计算任务
   * @param data The data for the request.
   * @param data.jobId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCalculationJob(
    data: Asm1DeleteCalculationJobData,
  ): CancelablePromise<Asm1DeleteCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/asm1/jobs/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Job Input Data
   * 获取ASM1计算任务的输入数据
   * @param data The data for the request.
   * @param data.jobId
   * @returns ASM1JobInputDataResponse Successful Response
   * @throws ApiError
   */
  public static getJobInputData(
    data: Asm1GetJobInputDataData,
  ): CancelablePromise<Asm1GetJobInputDataResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1/jobs/{job_id}/input-data",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class Asm1FlowchartsService {
  /**
   * Read Asm1 Flowcharts
   * Retrieve ASM1 flowcharts.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ASM1FlowChartsPublic Successful Response
   * @throws ApiError
   */
  public static readAsm1Flowcharts(
    data: Asm1FlowchartsReadAsm1FlowchartsData = {},
  ): CancelablePromise<Asm1FlowchartsReadAsm1FlowchartsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1-flowcharts/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Asm1 Flowchart
   * Create new ASM1 flowchart.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM1FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static createAsm1Flowchart(
    data: Asm1FlowchartsCreateAsm1FlowchartData,
  ): CancelablePromise<Asm1FlowchartsCreateAsm1FlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1-flowcharts/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Asm1 Flowchart
   * Get ASM1 flowchart by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ASM1FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static readAsm1Flowchart(
    data: Asm1FlowchartsReadAsm1FlowchartData,
  ): CancelablePromise<Asm1FlowchartsReadAsm1FlowchartResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Asm1 Flowchart
   * Update an ASM1 flowchart.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ASM1FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static updateAsm1Flowchart(
    data: Asm1FlowchartsUpdateAsm1FlowchartData,
  ): CancelablePromise<Asm1FlowchartsUpdateAsm1FlowchartResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/asm1-flowcharts/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Asm1 Flowchart
   * Delete an ASM1 flowchart.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteAsm1Flowchart(
    data: Asm1FlowchartsDeleteAsm1FlowchartData,
  ): CancelablePromise<Asm1FlowchartsDeleteAsm1FlowchartResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/asm1-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class Asm1SlimService {
  /**
   * Create Calculation Job
   * 创建ASM1slim计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM1SlimJobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJob(
    data: Asm1SlimCreateCalculationJobData,
  ): CancelablePromise<Asm1SlimCreateCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1slim/calculate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Calculation Job From Flowchart
   * 从流程图数据创建ASM1slim计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM1SlimJobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJobFromFlowchart(
    data: Asm1SlimCreateCalculationJobFromFlowchartData,
  ): CancelablePromise<Asm1SlimCreateCalculationJobFromFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1slim/calculate-from-flowchart",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Result Summary
   * 获取ASM1slim计算结果摘要
   * @param data The data for the request.
   * @param data.jobId
   * @returns MaterialBalanceResultSummary Successful Response
   * @throws ApiError
   */
  public static getCalculationResultSummary(
    data: Asm1SlimGetCalculationResultSummaryData,
  ): CancelablePromise<Asm1SlimGetCalculationResultSummaryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim/result/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Final Values
   * 获取ASM1slim计算的最终值
   * @param data The data for the request.
   * @param data.jobId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getCalculationFinalValues(
    data: Asm1SlimGetCalculationFinalValuesData,
  ): CancelablePromise<Asm1SlimGetCalculationFinalValuesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim/result/{job_id}/final-values",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Timeseries
   * 获取ASM1slim计算的时间序列数据
   * @param data The data for the request.
   * @param data.jobId
   * @param data.startTime 开始时间 (小时)
   * @param data.endTime 结束时间 (小时)
   * @param data.page 页码
   * @param data.pageSize 每页数据量
   * @param data.nodeIds 指定节点ID列表
   * @param data.edgeIds 指定边ID列表
   * @returns MaterialBalanceTimeSeriesResponse Successful Response
   * @throws ApiError
   */
  public static getCalculationTimeseries(
    data: Asm1SlimGetCalculationTimeseriesData,
  ): CancelablePromise<Asm1SlimGetCalculationTimeseriesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim/result/{job_id}/timeseries",
      path: {
        job_id: data.jobId,
      },
      query: {
        start_time: data.startTime,
        end_time: data.endTime,
        page: data.page,
        page_size: data.pageSize,
        node_ids: data.nodeIds,
        edge_ids: data.edgeIds,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Status
   * 获取ASM1slim计算任务状态
   * @param data The data for the request.
   * @param data.jobId
   * @returns ASM1SlimJobPublic Successful Response
   * @throws ApiError
   */
  public static getCalculationStatus(
    data: Asm1SlimGetCalculationStatusData,
  ): CancelablePromise<Asm1SlimGetCalculationStatusResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim/status/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Validate Calculation Input
   * 验证ASM1slim计算输入数据
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MaterialBalanceValidationResponse Successful Response
   * @throws ApiError
   */
  public static validateCalculationInput(
    data: Asm1SlimValidateCalculationInputData,
  ): CancelablePromise<Asm1SlimValidateCalculationInputResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1slim/validate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Calculation Jobs
   * 获取用户的ASM1slim计算任务列表
   * @param data The data for the request.
   * @param data.skip 跳过的记录数
   * @param data.limit 返回的记录数
   * @returns ASM1SlimJobsPublic Successful Response
   * @throws ApiError
   */
  public static getUserCalculationJobs(
    data: Asm1SlimGetUserCalculationJobsData = {},
  ): CancelablePromise<Asm1SlimGetUserCalculationJobsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim/jobs",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Calculation Job
   * 删除ASM1slim计算任务
   * @param data The data for the request.
   * @param data.jobId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCalculationJob(
    data: Asm1SlimDeleteCalculationJobData,
  ): CancelablePromise<Asm1SlimDeleteCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/asm1slim/jobs/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Job Input Data
   * 获取ASM1slim计算任务的输入数据
   * @param data The data for the request.
   * @param data.jobId
   * @returns ASM1SlimJobInputDataResponse Successful Response
   * @throws ApiError
   */
  public static getJobInputData(
    data: Asm1SlimGetJobInputDataData,
  ): CancelablePromise<Asm1SlimGetJobInputDataResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim/jobs/{job_id}/input-data",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class Asm1SlimFlowchartsService {
  /**
   * Read Asm1Slim Flowcharts
   * Retrieve ASM1Slim flowcharts.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ASM1SlimFlowChartsPublic Successful Response
   * @throws ApiError
   */
  public static readAsm1SlimFlowcharts(
    data: Asm1SlimFlowchartsReadAsm1SlimFlowchartsData = {},
  ): CancelablePromise<Asm1SlimFlowchartsReadAsm1SlimFlowchartsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim-flowcharts/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Asm1Slim Flowchart
   * Create new ASM1Slim flowchart.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM1SlimFlowChartPublic Successful Response
   * @throws ApiError
   */
  public static createAsm1SlimFlowchart(
    data: Asm1SlimFlowchartsCreateAsm1SlimFlowchartData,
  ): CancelablePromise<Asm1SlimFlowchartsCreateAsm1SlimFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1slim-flowcharts/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Asm1Slim Flowchart
   * Get ASM1Slim flowchart by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ASM1SlimFlowChartPublic Successful Response
   * @throws ApiError
   */
  public static readAsm1SlimFlowchart(
    data: Asm1SlimFlowchartsReadAsm1SlimFlowchartData,
  ): CancelablePromise<Asm1SlimFlowchartsReadAsm1SlimFlowchartResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Asm1Slim Flowchart
   * Update an ASM1Slim flowchart.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ASM1SlimFlowChartPublic Successful Response
   * @throws ApiError
   */
  public static updateAsm1SlimFlowchart(
    data: Asm1SlimFlowchartsUpdateAsm1SlimFlowchartData,
  ): CancelablePromise<Asm1SlimFlowchartsUpdateAsm1SlimFlowchartResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/asm1slim-flowcharts/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Asm1Slim Flowchart
   * Delete an ASM1Slim flowchart.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteAsm1SlimFlowchart(
    data: Asm1SlimFlowchartsDeleteAsm1SlimFlowchartData,
  ): CancelablePromise<Asm1SlimFlowchartsDeleteAsm1SlimFlowchartResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/asm1slim-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class Asm3Service {
  /**
   * Create Calculation Job
   * 创建ASM3计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM3JobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJob(
    data: Asm3CreateCalculationJobData,
  ): CancelablePromise<Asm3CreateCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm3/calculate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Calculation Job From Flowchart
   * 从流程图数据创建ASM3计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM3JobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJobFromFlowchart(
    data: Asm3CreateCalculationJobFromFlowchartData,
  ): CancelablePromise<Asm3CreateCalculationJobFromFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm3/calculate-from-flowchart",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Result Summary
   * 获取ASM3计算结果摘要
   * @param data The data for the request.
   * @param data.jobId
   * @returns MaterialBalanceResultSummary Successful Response
   * @throws ApiError
   */
  public static getCalculationResultSummary(
    data: Asm3GetCalculationResultSummaryData,
  ): CancelablePromise<Asm3GetCalculationResultSummaryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3/result/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Final Values
   * 获取ASM3计算的最终值
   * @param data The data for the request.
   * @param data.jobId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getCalculationFinalValues(
    data: Asm3GetCalculationFinalValuesData,
  ): CancelablePromise<Asm3GetCalculationFinalValuesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3/result/{job_id}/final-values",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Timeseries
   * 获取ASM3计算的时间序列数据
   * @param data The data for the request.
   * @param data.jobId
   * @param data.startTime 开始时间 (小时)
   * @param data.endTime 结束时间 (小时)
   * @param data.page 页码
   * @param data.pageSize 每页数据量
   * @param data.nodeIds 指定节点ID列表
   * @param data.edgeIds 指定边ID列表
   * @returns MaterialBalanceTimeSeriesResponse Successful Response
   * @throws ApiError
   */
  public static getCalculationTimeseries(
    data: Asm3GetCalculationTimeseriesData,
  ): CancelablePromise<Asm3GetCalculationTimeseriesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3/result/{job_id}/timeseries",
      path: {
        job_id: data.jobId,
      },
      query: {
        start_time: data.startTime,
        end_time: data.endTime,
        page: data.page,
        page_size: data.pageSize,
        node_ids: data.nodeIds,
        edge_ids: data.edgeIds,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Status
   * 获取ASM3计算任务状态
   * @param data The data for the request.
   * @param data.jobId
   * @returns ASM3JobPublic Successful Response
   * @throws ApiError
   */
  public static getCalculationStatus(
    data: Asm3GetCalculationStatusData,
  ): CancelablePromise<Asm3GetCalculationStatusResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3/status/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Validate Calculation Input
   * 验证ASM3计算输入数据
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MaterialBalanceValidationResponse Successful Response
   * @throws ApiError
   */
  public static validateCalculationInput(
    data: Asm3ValidateCalculationInputData,
  ): CancelablePromise<Asm3ValidateCalculationInputResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm3/validate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Calculation Jobs
   * 获取用户的ASM3计算任务列表
   * @param data The data for the request.
   * @param data.skip 跳过的记录数
   * @param data.limit 返回的记录数
   * @returns ASM3JobsPublic Successful Response
   * @throws ApiError
   */
  public static getUserCalculationJobs(
    data: Asm3GetUserCalculationJobsData = {},
  ): CancelablePromise<Asm3GetUserCalculationJobsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3/jobs",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Calculation Job
   * 删除ASM3计算任务
   * @param data The data for the request.
   * @param data.jobId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCalculationJob(
    data: Asm3DeleteCalculationJobData,
  ): CancelablePromise<Asm3DeleteCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/asm3/jobs/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Job Input Data
   * 获取ASM3计算任务的输入数据
   * @param data The data for the request.
   * @param data.jobId
   * @returns ASM3JobInputDataResponse Successful Response
   * @throws ApiError
   */
  public static getJobInputData(
    data: Asm3GetJobInputDataData,
  ): CancelablePromise<Asm3GetJobInputDataResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3/jobs/{job_id}/input-data",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class Asm3FlowchartsService {
  /**
   * Read Asm3 Flowcharts
   * Retrieve ASM3 flowcharts.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ASM3FlowChartsPublic Successful Response
   * @throws ApiError
   */
  public static readAsm3Flowcharts(
    data: Asm3FlowchartsReadAsm3FlowchartsData = {},
  ): CancelablePromise<Asm3FlowchartsReadAsm3FlowchartsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3-flowcharts/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Asm3 Flowchart
   * Create new ASM3 flowchart.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM3FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static createAsm3Flowchart(
    data: Asm3FlowchartsCreateAsm3FlowchartData,
  ): CancelablePromise<Asm3FlowchartsCreateAsm3FlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm3-flowcharts/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Asm3 Flowchart
   * Get ASM3 flowchart by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ASM3FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static readAsm3Flowchart(
    data: Asm3FlowchartsReadAsm3FlowchartData,
  ): CancelablePromise<Asm3FlowchartsReadAsm3FlowchartResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Asm3 Flowchart
   * Update an ASM3 flowchart.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ASM3FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static updateAsm3Flowchart(
    data: Asm3FlowchartsUpdateAsm3FlowchartData,
  ): CancelablePromise<Asm3FlowchartsUpdateAsm3FlowchartResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/asm3-flowcharts/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Asm3 Flowchart
   * Delete an ASM3 flowchart.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteAsm3Flowchart(
    data: Asm3FlowchartsDeleteAsm3FlowchartData,
  ): CancelablePromise<Asm3FlowchartsDeleteAsm3FlowchartResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/asm3-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class FlowchartsService {
  /**
   * Read Flowcharts
   * Retrieve flowcharts.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns FlowChartsPublic Successful Response
   * @throws ApiError
   */
  public static readFlowcharts(
    data: FlowchartsReadFlowchartsData = {},
  ): CancelablePromise<FlowchartsReadFlowchartsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/flowcharts/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Flowchart
   * Create new flowchart.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static createFlowchart(
    data: FlowchartsCreateFlowchartData,
  ): CancelablePromise<FlowchartsCreateFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/flowcharts/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Flowchart
   * Get flowchart by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static readFlowchart(
    data: FlowchartsReadFlowchartData,
  ): CancelablePromise<FlowchartsReadFlowchartResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Flowchart
   * Update a flowchart.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static updateFlowchart(
    data: FlowchartsUpdateFlowchartData,
  ): CancelablePromise<FlowchartsUpdateFlowchartResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/flowcharts/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Flowchart
   * Delete a flowchart.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteFlowchart(
    data: FlowchartsDeleteFlowchartData,
  ): CancelablePromise<FlowchartsDeleteFlowchartResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ItemsService {
  /**
   * Read Items
   * Retrieve items.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ItemsPublic Successful Response
   * @throws ApiError
   */
  public static readItems(
    data: ItemsReadItemsData = {},
  ): CancelablePromise<ItemsReadItemsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Item
   * Create new item.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static createItem(
    data: ItemsCreateItemData,
  ): CancelablePromise<ItemsCreateItemResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/items/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Item
   * Get item by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static readItem(
    data: ItemsReadItemData,
  ): CancelablePromise<ItemsReadItemResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Item
   * Update an item.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static updateItem(
    data: ItemsUpdateItemData,
  ): CancelablePromise<ItemsUpdateItemResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Item
   * Delete an item.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteItem(
    data: ItemsDeleteItemData,
  ): CancelablePromise<ItemsDeleteItemResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData,
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<LoginTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/test-token",
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData,
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData,
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: LoginRecoverPasswordHtmlContentData,
  ): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class MaterialBalanceService {
  /**
   * Create Calculation Job
   * 创建物料平衡计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MaterialBalanceJobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJob(
    data: MaterialBalanceCreateCalculationJobData,
  ): CancelablePromise<MaterialBalanceCreateCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/material-balance/calculate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Calculation Job From Flowchart
   * 从流程图数据创建物料平衡计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MaterialBalanceJobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJobFromFlowchart(
    data: MaterialBalanceCreateCalculationJobFromFlowchartData,
  ): CancelablePromise<MaterialBalanceCreateCalculationJobFromFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/material-balance/calculate-from-flowchart",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Result Summary
   * 获取计算结果摘要
   * @param data The data for the request.
   * @param data.jobId
   * @returns MaterialBalanceResultSummary Successful Response
   * @throws ApiError
   */
  public static getCalculationResultSummary(
    data: MaterialBalanceGetCalculationResultSummaryData,
  ): CancelablePromise<MaterialBalanceGetCalculationResultSummaryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/material-balance/result/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Final Values
   * 获取计算结果中数组的最后一位数据（最终状态）
   * @param data The data for the request.
   * @param data.jobId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getCalculationFinalValues(
    data: MaterialBalanceGetCalculationFinalValuesData,
  ): CancelablePromise<MaterialBalanceGetCalculationFinalValuesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/material-balance/result/{job_id}/final-values",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Timeseries
   * 分页获取时间序列数据
   * @param data The data for the request.
   * @param data.jobId
   * @param data.startTime 开始时间 (小时)
   * @param data.endTime 结束时间 (小时)
   * @param data.page 页码
   * @param data.pageSize 每页数据量
   * @param data.nodeIds 指定节点ID列表
   * @param data.edgeIds 指定边ID列表
   * @returns MaterialBalanceTimeSeriesResponse Successful Response
   * @throws ApiError
   */
  public static getCalculationTimeseries(
    data: MaterialBalanceGetCalculationTimeseriesData,
  ): CancelablePromise<MaterialBalanceGetCalculationTimeseriesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/material-balance/result/{job_id}/timeseries",
      path: {
        job_id: data.jobId,
      },
      query: {
        start_time: data.startTime,
        end_time: data.endTime,
        page: data.page,
        page_size: data.pageSize,
        node_ids: data.nodeIds,
        edge_ids: data.edgeIds,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Status
   * 查询计算状态
   * @param data The data for the request.
   * @param data.jobId
   * @returns MaterialBalanceJobPublic Successful Response
   * @throws ApiError
   */
  public static getCalculationStatus(
    data: MaterialBalanceGetCalculationStatusData,
  ): CancelablePromise<MaterialBalanceGetCalculationStatusResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/material-balance/status/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Validate Calculation Input
   * 验证输入参数
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MaterialBalanceValidationResponse Successful Response
   * @throws ApiError
   */
  public static validateCalculationInput(
    data: MaterialBalanceValidateCalculationInputData,
  ): CancelablePromise<MaterialBalanceValidateCalculationInputResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/material-balance/validate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Calculation Jobs
   * 获取用户的计算任务列表
   * @param data The data for the request.
   * @param data.skip 跳过的记录数
   * @param data.limit 返回的记录数
   * @returns MaterialBalanceJobsPublic Successful Response
   * @throws ApiError
   */
  public static getUserCalculationJobs(
    data: MaterialBalanceGetUserCalculationJobsData = {},
  ): CancelablePromise<MaterialBalanceGetUserCalculationJobsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/material-balance/jobs",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Calculation Job
   * 删除计算任务
   * @param data The data for the request.
   * @param data.jobId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCalculationJob(
    data: MaterialBalanceDeleteCalculationJobData,
  ): CancelablePromise<MaterialBalanceDeleteCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/material-balance/jobs/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Job Input Data
   * 获取计算任务的输入数据
   * @param data The data for the request.
   * @param data.jobId
   * @returns MaterialBalanceJobInputDataResponse Successful Response
   * @throws ApiError
   */
  public static getJobInputData(
    data: MaterialBalanceGetJobInputDataData,
  ): CancelablePromise<MaterialBalanceGetJobInputDataResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/material-balance/jobs/{job_id}/input-data",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: PrivateCreateUserData,
  ): CancelablePromise<PrivateCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/private/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class SimpleWebsocketService {
  /**
   * Get Task Connections
   * 获取指定任务的WebSocket连接信息
   *
   * Args:
   * task_id: 任务ID
   *
   * Returns:
   * 连接信息
   * @param data The data for the request.
   * @param data.taskId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getTaskConnections(
    data: SimpleWebsocketGetTaskConnectionsData,
  ): CancelablePromise<SimpleWebsocketGetTaskConnectionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/simple-ws/connections/{task_id}",
      path: {
        task_id: data.taskId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Broadcast Message
   * 向指定任务的所有连接广播消息
   *
   * Args:
   * task_id: 任务ID
   * message: 要广播的消息
   *
   * Returns:
   * 广播结果
   * @param data The data for the request.
   * @param data.taskId
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static broadcastMessage(
    data: SimpleWebsocketBroadcastMessageData,
  ): CancelablePromise<SimpleWebsocketBroadcastMessageResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/simple-ws/broadcast/{task_id}",
      path: {
        task_id: data.taskId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Websocket Health
   * WebSocket服务健康检查
   *
   * Returns:
   * 健康状态
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static websocketHealth(): CancelablePromise<SimpleWebsocketWebsocketHealthResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/simple-ws/health",
    })
  }
}

export class StatsService {
  /**
   * Get Dashboard Stats
   * 获取超级用户dashboard统计数据
   * 只有超级用户可以访问此接口
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getDashboardStats(): CancelablePromise<StatsGetDashboardStatsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/stats/dashboard",
    })
  }

  /**
   * Get User Stats
   * 获取详细的用户统计信息
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getUserStats(): CancelablePromise<StatsGetUserStatsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/stats/users",
    })
  }
}

export class UdmService {
  /**
   * Create Calculation Job
   * 创建UDM计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UDMJobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJob(
    data: UdmCreateCalculationJobData,
  ): CancelablePromise<UdmCreateCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/udm/calculate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Calculation Job From Flowchart
   * 从流程图数据创建UDM计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UDMJobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJobFromFlowchart(
    data: UdmCreateCalculationJobFromFlowchartData,
  ): CancelablePromise<UdmCreateCalculationJobFromFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/udm/calculate-from-flowchart",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Result Summary
   * 获取UDM计算结果摘要
   * @param data The data for the request.
   * @param data.jobId
   * @returns MaterialBalanceResultSummary Successful Response
   * @throws ApiError
   */
  public static getCalculationResultSummary(
    data: UdmGetCalculationResultSummaryData,
  ): CancelablePromise<UdmGetCalculationResultSummaryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/udm/result/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Final Values
   * 获取UDM计算的最终值
   * @param data The data for the request.
   * @param data.jobId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getCalculationFinalValues(
    data: UdmGetCalculationFinalValuesData,
  ): CancelablePromise<UdmGetCalculationFinalValuesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/udm/result/{job_id}/final-values",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Timeseries
   * 获取UDM计算的时间序列数据
   * @param data The data for the request.
   * @param data.jobId
   * @param data.startTime 开始时间 (小时)
   * @param data.endTime 结束时间 (小时)
   * @param data.page 页码
   * @param data.pageSize 每页数据量
   * @param data.nodeIds 指定节点ID列表
   * @param data.edgeIds 指定边ID列表
   * @returns MaterialBalanceTimeSeriesResponse Successful Response
   * @throws ApiError
   */
  public static getCalculationTimeseries(
    data: UdmGetCalculationTimeseriesData,
  ): CancelablePromise<UdmGetCalculationTimeseriesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/udm/result/{job_id}/timeseries",
      path: {
        job_id: data.jobId,
      },
      query: {
        start_time: data.startTime,
        end_time: data.endTime,
        page: data.page,
        page_size: data.pageSize,
        node_ids: data.nodeIds,
        edge_ids: data.edgeIds,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Status
   * 获取UDM计算任务状态
   * @param data The data for the request.
   * @param data.jobId
   * @returns UDMJobPublic Successful Response
   * @throws ApiError
   */
  public static getCalculationStatus(
    data: UdmGetCalculationStatusData,
  ): CancelablePromise<UdmGetCalculationStatusResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/udm/status/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Validate Calculation Input
   * 验证UDM计算输入数据
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MaterialBalanceValidationResponse Successful Response
   * @throws ApiError
   */
  public static validateCalculationInput(
    data: UdmValidateCalculationInputData,
  ): CancelablePromise<UdmValidateCalculationInputResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/udm/validate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Calculation Jobs
   * 获取用户的UDM计算任务列表
   * @param data The data for the request.
   * @param data.skip 跳过的记录数
   * @param data.limit 返回的记录数
   * @returns UDMJobsPublic Successful Response
   * @throws ApiError
   */
  public static getUserCalculationJobs(
    data: UdmGetUserCalculationJobsData = {},
  ): CancelablePromise<UdmGetUserCalculationJobsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/udm/jobs",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Calculation Job
   * 删除UDM计算任务
   * @param data The data for the request.
   * @param data.jobId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCalculationJob(
    data: UdmDeleteCalculationJobData,
  ): CancelablePromise<UdmDeleteCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/udm/jobs/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Job Input Data
   * 获取UDM计算任务的输入数据
   * @param data The data for the request.
   * @param data.jobId
   * @returns UDMJobInputDataResponse Successful Response
   * @throws ApiError
   */
  public static getJobInputData(
    data: UdmGetJobInputDataData,
  ): CancelablePromise<UdmGetJobInputDataResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/udm/jobs/{job_id}/input-data",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UdmFlowchartsService {
  /**
   * Read Udm Flowcharts
   * Retrieve UDM flowcharts.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UDMFlowChartsPublic Successful Response
   * @throws ApiError
   */
  public static readUdmFlowcharts(
    data: UdmFlowchartsReadUdmFlowchartsData = {},
  ): CancelablePromise<UdmFlowchartsReadUdmFlowchartsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/udm-flowcharts/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Udm Flowchart
   * Create new UDM flowchart.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UDMFlowChartPublic Successful Response
   * @throws ApiError
   */
  public static createUdmFlowchart(
    data: UdmFlowchartsCreateUdmFlowchartData,
  ): CancelablePromise<UdmFlowchartsCreateUdmFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/udm-flowcharts/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Udm Flowchart
   * Get UDM flowchart by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns UDMFlowChartPublic Successful Response
   * @throws ApiError
   */
  public static readUdmFlowchart(
    data: UdmFlowchartsReadUdmFlowchartData,
  ): CancelablePromise<UdmFlowchartsReadUdmFlowchartResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/udm-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Udm Flowchart
   * Update an UDM flowchart.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns UDMFlowChartPublic Successful Response
   * @throws ApiError
   */
  public static updateUdmFlowchart(
    data: UdmFlowchartsUpdateUdmFlowchartData,
  ): CancelablePromise<UdmFlowchartsUpdateUdmFlowchartResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/udm-flowcharts/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Udm Flowchart
   * Delete an UDM flowchart.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUdmFlowchart(
    data: UdmFlowchartsDeleteUdmFlowchartData,
  ): CancelablePromise<UdmFlowchartsDeleteUdmFlowchartResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/udm-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UdmModelsService {
  /**
   * Get Udm Templates
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getUdmTemplates(): CancelablePromise<UdmModelsGetUdmTemplatesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/udm-models/templates",
    })
  }

  /**
   * Validate Udm Model Definition
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UDMValidationResponse Successful Response
   * @throws ApiError
   */
  public static validateUdmModelDefinition(
    data: UdmModelsValidateUdmModelDefinitionData,
  ): CancelablePromise<UdmModelsValidateUdmModelDefinitionResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/udm-models/validate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Udm Model
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UDMModelDetailPublic Successful Response
   * @throws ApiError
   */
  public static createUdmModel(
    data: UdmModelsCreateUdmModelData,
  ): CancelablePromise<UdmModelsCreateUdmModelResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/udm-models/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Udm Models
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @param data.q Search by model name
   * @returns UDMModelsPublic Successful Response
   * @throws ApiError
   */
  public static readUdmModels(
    data: UdmModelsReadUdmModelsData = {},
  ): CancelablePromise<UdmModelsReadUdmModelsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/udm-models/",
      query: {
        skip: data.skip,
        limit: data.limit,
        q: data.q,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Udm Model From Template
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UDMModelDetailPublic Successful Response
   * @throws ApiError
   */
  public static createUdmModelFromTemplate(
    data: UdmModelsCreateUdmModelFromTemplateData,
  ): CancelablePromise<UdmModelsCreateUdmModelFromTemplateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/udm-models/from-template",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Udm Model
   * @param data The data for the request.
   * @param data.modelId
   * @returns UDMModelDetailPublic Successful Response
   * @throws ApiError
   */
  public static readUdmModel(
    data: UdmModelsReadUdmModelData,
  ): CancelablePromise<UdmModelsReadUdmModelResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/udm-models/{model_id}",
      path: {
        model_id: data.modelId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Udm Model
   * @param data The data for the request.
   * @param data.modelId
   * @param data.requestBody
   * @returns UDMModelDetailPublic Successful Response
   * @throws ApiError
   */
  public static updateUdmModel(
    data: UdmModelsUpdateUdmModelData,
  ): CancelablePromise<UdmModelsUpdateUdmModelResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/udm-models/{model_id}",
      path: {
        model_id: data.modelId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Udm Model
   * @param data The data for the request.
   * @param data.modelId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUdmModel(
    data: UdmModelsDeleteUdmModelData,
  ): CancelablePromise<UdmModelsDeleteUdmModelResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/udm-models/{model_id}",
      path: {
        model_id: data.modelId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Read Users
   * Retrieve users.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: UsersReadUsersData = {},
  ): CancelablePromise<UsersReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create User
   * Create new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: UsersCreateUserData,
  ): CancelablePromise<UsersCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User Me
   * Get current user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * Delete own user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * Update own user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData,
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * Update own password.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UsersUpdatePasswordMeData,
  ): CancelablePromise<UsersUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register User
   * Create new user without the need to be logged in.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: UsersRegisterUserData,
  ): CancelablePromise<UsersRegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * Get a specific user by id.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: UsersReadUserByIdData,
  ): CancelablePromise<UsersReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User
   * Update a user.
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UsersUpdateUserData,
  ): CancelablePromise<UsersUpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User
   * Delete a user.
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: UsersDeleteUserData,
  ): CancelablePromise<UsersDeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: UtilsTestEmailData,
  ): CancelablePromise<UtilsTestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/test-email/",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Health Check
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    })
  }
}
