// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  Asm1CreateCalculationJobData,
  Asm1CreateCalculationJobFromFlowchartData,
  Asm1CreateCalculationJobFromFlowchartResponse,
  Asm1CreateCalculationJobResponse,
  Asm1DeleteCalculationJobData,
  Asm1DeleteCalculationJobResponse,
  Asm1FlowchartsCreateAsm1FlowchartData,
  Asm1FlowchartsCreateAsm1FlowchartResponse,
  Asm1FlowchartsDeleteAsm1FlowchartData,
  Asm1FlowchartsDeleteAsm1FlowchartResponse,
  Asm1FlowchartsReadAsm1FlowchartData,
  Asm1FlowchartsReadAsm1FlowchartResponse,
  Asm1FlowchartsReadAsm1FlowchartsData,
  Asm1FlowchartsReadAsm1FlowchartsResponse,
  Asm1FlowchartsUpdateAsm1FlowchartData,
  Asm1FlowchartsUpdateAsm1FlowchartResponse,
  Asm1GetCalculationFinalValuesData,
  Asm1GetCalculationFinalValuesResponse,
  Asm1GetCalculationResultSummaryData,
  Asm1GetCalculationResultSummaryResponse,
  Asm1GetCalculationStatusData,
  Asm1GetCalculationStatusResponse,
  Asm1GetCalculationTimeseriesData,
  Asm1GetCalculationTimeseriesResponse,
  Asm1GetJobInputDataData,
  Asm1GetJobInputDataResponse,
  Asm1GetUserCalculationJobsData,
  Asm1GetUserCalculationJobsResponse,
  Asm1SlimCreateCalculationJobData,
  Asm1SlimCreateCalculationJobFromFlowchartData,
  Asm1SlimCreateCalculationJobFromFlowchartResponse,
  Asm1SlimCreateCalculationJobResponse,
  Asm1SlimDeleteCalculationJobData,
  Asm1SlimDeleteCalculationJobResponse,
  Asm1SlimFlowchartsCreateAsm1SlimFlowchartData,
  Asm1SlimFlowchartsCreateAsm1SlimFlowchartResponse,
  Asm1SlimFlowchartsDeleteAsm1SlimFlowchartData,
  Asm1SlimFlowchartsDeleteAsm1SlimFlowchartResponse,
  Asm1SlimFlowchartsReadAsm1SlimFlowchartData,
  Asm1SlimFlowchartsReadAsm1SlimFlowchartResponse,
  Asm1SlimFlowchartsReadAsm1SlimFlowchartsData,
  Asm1SlimFlowchartsReadAsm1SlimFlowchartsResponse,
  Asm1SlimFlowchartsUpdateAsm1SlimFlowchartData,
  Asm1SlimFlowchartsUpdateAsm1SlimFlowchartResponse,
  Asm1SlimGetCalculationFinalValuesData,
  Asm1SlimGetCalculationFinalValuesResponse,
  Asm1SlimGetCalculationResultSummaryData,
  Asm1SlimGetCalculationResultSummaryResponse,
  Asm1SlimGetCalculationStatusData,
  Asm1SlimGetCalculationStatusResponse,
  Asm1SlimGetCalculationTimeseriesData,
  Asm1SlimGetCalculationTimeseriesResponse,
  Asm1SlimGetJobInputDataData,
  Asm1SlimGetJobInputDataResponse,
  Asm1SlimGetUserCalculationJobsData,
  Asm1SlimGetUserCalculationJobsResponse,
  Asm1SlimValidateCalculationInputData,
  Asm1SlimValidateCalculationInputResponse,
  Asm1ValidateCalculationInputData,
  Asm1ValidateCalculationInputResponse,
  Asm3CreateCalculationJobData,
  Asm3CreateCalculationJobFromFlowchartData,
  Asm3CreateCalculationJobFromFlowchartResponse,
  Asm3CreateCalculationJobResponse,
  Asm3DeleteCalculationJobData,
  Asm3DeleteCalculationJobResponse,
  Asm3FlowchartsCreateAsm3FlowchartData,
  Asm3FlowchartsCreateAsm3FlowchartResponse,
  Asm3FlowchartsDeleteAsm3FlowchartData,
  Asm3FlowchartsDeleteAsm3FlowchartResponse,
  Asm3FlowchartsReadAsm3FlowchartData,
  Asm3FlowchartsReadAsm3FlowchartResponse,
  Asm3FlowchartsReadAsm3FlowchartsData,
  Asm3FlowchartsReadAsm3FlowchartsResponse,
  Asm3FlowchartsUpdateAsm3FlowchartData,
  Asm3FlowchartsUpdateAsm3FlowchartResponse,
  Asm3GetCalculationFinalValuesData,
  Asm3GetCalculationFinalValuesResponse,
  Asm3GetCalculationResultSummaryData,
  Asm3GetCalculationResultSummaryResponse,
  Asm3GetCalculationStatusData,
  Asm3GetCalculationStatusResponse,
  Asm3GetCalculationTimeseriesData,
  Asm3GetCalculationTimeseriesResponse,
  Asm3GetJobInputDataData,
  Asm3GetJobInputDataResponse,
  Asm3GetUserCalculationJobsData,
  Asm3GetUserCalculationJobsResponse,
  Asm3ValidateCalculationInputData,
  Asm3ValidateCalculationInputResponse,
  DataAnalysisCancelAnalysisTaskData,
  DataAnalysisCancelAnalysisTaskResponse,
  DataAnalysisCreateAnalysisTaskAliasData,
  DataAnalysisCreateAnalysisTaskAliasResponse,
  DataAnalysisCreateAnalysisTaskData,
  DataAnalysisCreateAnalysisTaskResponse,
  DataAnalysisDeleteAnalysisTaskData,
  DataAnalysisDeleteAnalysisTaskResponse,
  DataAnalysisDeleteFileEndpointData,
  DataAnalysisDeleteFileEndpointResponse,
  DataAnalysisDownloadExportData,
  DataAnalysisDownloadExportResponse,
  DataAnalysisExportResultData,
  DataAnalysisExportResultResponse,
  DataAnalysisGetAnalysisStatsResponse,
  DataAnalysisGetAnalysisTaskData,
  DataAnalysisGetAnalysisTaskResponse,
  DataAnalysisGetAnalysisTasksData,
  DataAnalysisGetAnalysisTasksResponse,
  DataAnalysisGetBasicStatsData,
  DataAnalysisGetBasicStatsResponse,
  DataAnalysisGetFileData,
  DataAnalysisGetFileResponse,
  DataAnalysisGetFileSchemaData,
  DataAnalysisGetFileSchemaResponse,
  DataAnalysisGetFilesData,
  DataAnalysisGetFilesResponse,
  DataAnalysisGetResultData,
  DataAnalysisGetResultResponse,
  DataAnalysisGetSystemHealthResponse,
  DataAnalysisGetTaskProgressEndpointData,
  DataAnalysisGetTaskProgressEndpointResponse,
  DataAnalysisGetTaskResultsData,
  DataAnalysisGetTaskResultsQuickData,
  DataAnalysisGetTaskResultsQuickResponse,
  DataAnalysisGetTaskResultsResponse,
  DataAnalysisGetTaskStatusQuickData,
  DataAnalysisGetTaskStatusQuickResponse,
  DataAnalysisGetUploadPolicyResponse,
  DataAnalysisPreviewFileData,
  DataAnalysisPreviewFileResponse,
  DataAnalysisUpdateAnalysisTaskData,
  DataAnalysisUpdateAnalysisTaskResponse,
  DataAnalysisUploadFileAliasData,
  DataAnalysisUploadFileAliasResponse,
  DataAnalysisUploadFileData,
  DataAnalysisUploadFileResponse,
  DataAnalysisValidateAnalysisConfigData,
  DataAnalysisValidateAnalysisConfigResponse,
  FlowchartsCreateFlowchartData,
  FlowchartsCreateFlowchartResponse,
  FlowchartsDeleteFlowchartData,
  FlowchartsDeleteFlowchartResponse,
  FlowchartsReadFlowchartData,
  FlowchartsReadFlowchartResponse,
  FlowchartsReadFlowchartsData,
  FlowchartsReadFlowchartsResponse,
  FlowchartsUpdateFlowchartData,
  FlowchartsUpdateFlowchartResponse,
  ItemsCreateItemData,
  ItemsCreateItemResponse,
  ItemsDeleteItemData,
  ItemsDeleteItemResponse,
  ItemsReadItemData,
  ItemsReadItemResponse,
  ItemsReadItemsData,
  ItemsReadItemsResponse,
  ItemsUpdateItemData,
  ItemsUpdateItemResponse,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentResponse,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  LoginTestTokenResponse,
  MaterialBalanceCreateCalculationJobData,
  MaterialBalanceCreateCalculationJobFromFlowchartData,
  MaterialBalanceCreateCalculationJobFromFlowchartResponse,
  MaterialBalanceCreateCalculationJobResponse,
  MaterialBalanceDeleteCalculationJobData,
  MaterialBalanceDeleteCalculationJobResponse,
  MaterialBalanceGetCalculationFinalValuesData,
  MaterialBalanceGetCalculationFinalValuesResponse,
  MaterialBalanceGetCalculationResultSummaryData,
  MaterialBalanceGetCalculationResultSummaryResponse,
  MaterialBalanceGetCalculationStatusData,
  MaterialBalanceGetCalculationStatusResponse,
  MaterialBalanceGetCalculationTimeseriesData,
  MaterialBalanceGetCalculationTimeseriesResponse,
  MaterialBalanceGetJobInputDataData,
  MaterialBalanceGetJobInputDataResponse,
  MaterialBalanceGetUserCalculationJobsData,
  MaterialBalanceGetUserCalculationJobsResponse,
  MaterialBalanceValidateCalculationInputData,
  MaterialBalanceValidateCalculationInputResponse,
  PrivateCreateUserData,
  PrivateCreateUserResponse,
  SimpleWebsocketBroadcastMessageData,
  SimpleWebsocketBroadcastMessageResponse,
  SimpleWebsocketGetTaskConnectionsData,
  SimpleWebsocketGetTaskConnectionsResponse,
  SimpleWebsocketWebsocketHealthResponse,
  StatsGetDashboardStatsResponse,
  StatsGetUserStatsResponse,
  UsersCreateUserData,
  UsersCreateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserMeResponse,
  UsersDeleteUserResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdResponse,
  UsersReadUserMeResponse,
  UsersReadUsersData,
  UsersReadUsersResponse,
  UsersRegisterUserData,
  UsersRegisterUserResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeResponse,
  UsersUpdateUserData,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UsersUpdateUserResponse,
  UtilsHealthCheckResponse,
  UtilsTestEmailData,
  UtilsTestEmailResponse,
  WebsocketGetWebsocketStatsResponse,
  WebsocketTestSendCompletionData,
  WebsocketTestSendCompletionResponse,
  WebsocketTestSendProgressData,
  WebsocketTestSendProgressResponse,
} from "./types.gen"

export class Asm1Service {
  /**
   * Create Calculation Job
   * 创建ASM1计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM1JobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJob(
    data: Asm1CreateCalculationJobData,
  ): CancelablePromise<Asm1CreateCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1/calculate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Calculation Job From Flowchart
   * 从流程图数据创建ASM1计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM1JobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJobFromFlowchart(
    data: Asm1CreateCalculationJobFromFlowchartData,
  ): CancelablePromise<Asm1CreateCalculationJobFromFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1/calculate-from-flowchart",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Result Summary
   * 获取ASM1计算结果摘要
   * @param data The data for the request.
   * @param data.jobId
   * @returns MaterialBalanceResultSummary Successful Response
   * @throws ApiError
   */
  public static getCalculationResultSummary(
    data: Asm1GetCalculationResultSummaryData,
  ): CancelablePromise<Asm1GetCalculationResultSummaryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1/result/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Final Values
   * 获取ASM1计算的最终值
   * @param data The data for the request.
   * @param data.jobId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getCalculationFinalValues(
    data: Asm1GetCalculationFinalValuesData,
  ): CancelablePromise<Asm1GetCalculationFinalValuesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1/result/{job_id}/final-values",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Timeseries
   * 获取ASM1计算的时间序列数据
   * @param data The data for the request.
   * @param data.jobId
   * @param data.startTime 开始时间 (小时)
   * @param data.endTime 结束时间 (小时)
   * @param data.page 页码
   * @param data.pageSize 每页数据量
   * @param data.nodeIds 指定节点ID列表
   * @param data.edgeIds 指定边ID列表
   * @returns MaterialBalanceTimeSeriesResponse Successful Response
   * @throws ApiError
   */
  public static getCalculationTimeseries(
    data: Asm1GetCalculationTimeseriesData,
  ): CancelablePromise<Asm1GetCalculationTimeseriesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1/result/{job_id}/timeseries",
      path: {
        job_id: data.jobId,
      },
      query: {
        start_time: data.startTime,
        end_time: data.endTime,
        page: data.page,
        page_size: data.pageSize,
        node_ids: data.nodeIds,
        edge_ids: data.edgeIds,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Status
   * 获取ASM1计算任务状态
   * @param data The data for the request.
   * @param data.jobId
   * @returns ASM1JobPublic Successful Response
   * @throws ApiError
   */
  public static getCalculationStatus(
    data: Asm1GetCalculationStatusData,
  ): CancelablePromise<Asm1GetCalculationStatusResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1/status/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Validate Calculation Input
   * 验证ASM1计算输入数据
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MaterialBalanceValidationResponse Successful Response
   * @throws ApiError
   */
  public static validateCalculationInput(
    data: Asm1ValidateCalculationInputData,
  ): CancelablePromise<Asm1ValidateCalculationInputResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1/validate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Calculation Jobs
   * 获取用户的ASM1计算任务列表
   * @param data The data for the request.
   * @param data.skip 跳过的记录数
   * @param data.limit 返回的记录数
   * @returns ASM1JobsPublic Successful Response
   * @throws ApiError
   */
  public static getUserCalculationJobs(
    data: Asm1GetUserCalculationJobsData = {},
  ): CancelablePromise<Asm1GetUserCalculationJobsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1/jobs",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Calculation Job
   * 删除ASM1计算任务
   * @param data The data for the request.
   * @param data.jobId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCalculationJob(
    data: Asm1DeleteCalculationJobData,
  ): CancelablePromise<Asm1DeleteCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/asm1/jobs/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Job Input Data
   * 获取ASM1计算任务的输入数据
   * @param data The data for the request.
   * @param data.jobId
   * @returns ASM1JobInputDataResponse Successful Response
   * @throws ApiError
   */
  public static getJobInputData(
    data: Asm1GetJobInputDataData,
  ): CancelablePromise<Asm1GetJobInputDataResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1/jobs/{job_id}/input-data",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class Asm1FlowchartsService {
  /**
   * Read Asm1 Flowcharts
   * Retrieve ASM1 flowcharts.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ASM1FlowChartsPublic Successful Response
   * @throws ApiError
   */
  public static readAsm1Flowcharts(
    data: Asm1FlowchartsReadAsm1FlowchartsData = {},
  ): CancelablePromise<Asm1FlowchartsReadAsm1FlowchartsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1-flowcharts/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Asm1 Flowchart
   * Create new ASM1 flowchart.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM1FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static createAsm1Flowchart(
    data: Asm1FlowchartsCreateAsm1FlowchartData,
  ): CancelablePromise<Asm1FlowchartsCreateAsm1FlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1-flowcharts/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Asm1 Flowchart
   * Get ASM1 flowchart by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ASM1FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static readAsm1Flowchart(
    data: Asm1FlowchartsReadAsm1FlowchartData,
  ): CancelablePromise<Asm1FlowchartsReadAsm1FlowchartResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Asm1 Flowchart
   * Update an ASM1 flowchart.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ASM1FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static updateAsm1Flowchart(
    data: Asm1FlowchartsUpdateAsm1FlowchartData,
  ): CancelablePromise<Asm1FlowchartsUpdateAsm1FlowchartResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/asm1-flowcharts/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Asm1 Flowchart
   * Delete an ASM1 flowchart.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteAsm1Flowchart(
    data: Asm1FlowchartsDeleteAsm1FlowchartData,
  ): CancelablePromise<Asm1FlowchartsDeleteAsm1FlowchartResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/asm1-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class Asm1SlimService {
  /**
   * Create Calculation Job
   * 创建ASM1slim计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM1SlimJobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJob(
    data: Asm1SlimCreateCalculationJobData,
  ): CancelablePromise<Asm1SlimCreateCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1slim/calculate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Calculation Job From Flowchart
   * 从流程图数据创建ASM1slim计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM1SlimJobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJobFromFlowchart(
    data: Asm1SlimCreateCalculationJobFromFlowchartData,
  ): CancelablePromise<Asm1SlimCreateCalculationJobFromFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1slim/calculate-from-flowchart",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Result Summary
   * 获取ASM1slim计算结果摘要
   * @param data The data for the request.
   * @param data.jobId
   * @returns MaterialBalanceResultSummary Successful Response
   * @throws ApiError
   */
  public static getCalculationResultSummary(
    data: Asm1SlimGetCalculationResultSummaryData,
  ): CancelablePromise<Asm1SlimGetCalculationResultSummaryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim/result/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Final Values
   * 获取ASM1slim计算的最终值
   * @param data The data for the request.
   * @param data.jobId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getCalculationFinalValues(
    data: Asm1SlimGetCalculationFinalValuesData,
  ): CancelablePromise<Asm1SlimGetCalculationFinalValuesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim/result/{job_id}/final-values",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Timeseries
   * 获取ASM1slim计算的时间序列数据
   * @param data The data for the request.
   * @param data.jobId
   * @param data.startTime 开始时间 (小时)
   * @param data.endTime 结束时间 (小时)
   * @param data.page 页码
   * @param data.pageSize 每页数据量
   * @param data.nodeIds 指定节点ID列表
   * @param data.edgeIds 指定边ID列表
   * @returns MaterialBalanceTimeSeriesResponse Successful Response
   * @throws ApiError
   */
  public static getCalculationTimeseries(
    data: Asm1SlimGetCalculationTimeseriesData,
  ): CancelablePromise<Asm1SlimGetCalculationTimeseriesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim/result/{job_id}/timeseries",
      path: {
        job_id: data.jobId,
      },
      query: {
        start_time: data.startTime,
        end_time: data.endTime,
        page: data.page,
        page_size: data.pageSize,
        node_ids: data.nodeIds,
        edge_ids: data.edgeIds,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Status
   * 获取ASM1slim计算任务状态
   * @param data The data for the request.
   * @param data.jobId
   * @returns ASM1SlimJobPublic Successful Response
   * @throws ApiError
   */
  public static getCalculationStatus(
    data: Asm1SlimGetCalculationStatusData,
  ): CancelablePromise<Asm1SlimGetCalculationStatusResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim/status/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Validate Calculation Input
   * 验证ASM1slim计算输入数据
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MaterialBalanceValidationResponse Successful Response
   * @throws ApiError
   */
  public static validateCalculationInput(
    data: Asm1SlimValidateCalculationInputData,
  ): CancelablePromise<Asm1SlimValidateCalculationInputResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1slim/validate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Calculation Jobs
   * 获取用户的ASM1slim计算任务列表
   * @param data The data for the request.
   * @param data.skip 跳过的记录数
   * @param data.limit 返回的记录数
   * @returns ASM1SlimJobsPublic Successful Response
   * @throws ApiError
   */
  public static getUserCalculationJobs(
    data: Asm1SlimGetUserCalculationJobsData = {},
  ): CancelablePromise<Asm1SlimGetUserCalculationJobsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim/jobs",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Calculation Job
   * 删除ASM1slim计算任务
   * @param data The data for the request.
   * @param data.jobId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCalculationJob(
    data: Asm1SlimDeleteCalculationJobData,
  ): CancelablePromise<Asm1SlimDeleteCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/asm1slim/jobs/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Job Input Data
   * 获取ASM1slim计算任务的输入数据
   * @param data The data for the request.
   * @param data.jobId
   * @returns ASM1SlimJobInputDataResponse Successful Response
   * @throws ApiError
   */
  public static getJobInputData(
    data: Asm1SlimGetJobInputDataData,
  ): CancelablePromise<Asm1SlimGetJobInputDataResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim/jobs/{job_id}/input-data",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class Asm1SlimFlowchartsService {
  /**
   * Read Asm1Slim Flowcharts
   * Retrieve ASM1Slim flowcharts.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ASM1SlimFlowChartsPublic Successful Response
   * @throws ApiError
   */
  public static readAsm1SlimFlowcharts(
    data: Asm1SlimFlowchartsReadAsm1SlimFlowchartsData = {},
  ): CancelablePromise<Asm1SlimFlowchartsReadAsm1SlimFlowchartsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim-flowcharts/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Asm1Slim Flowchart
   * Create new ASM1Slim flowchart.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM1SlimFlowChartPublic Successful Response
   * @throws ApiError
   */
  public static createAsm1SlimFlowchart(
    data: Asm1SlimFlowchartsCreateAsm1SlimFlowchartData,
  ): CancelablePromise<Asm1SlimFlowchartsCreateAsm1SlimFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm1slim-flowcharts/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Asm1Slim Flowchart
   * Get ASM1Slim flowchart by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ASM1SlimFlowChartPublic Successful Response
   * @throws ApiError
   */
  public static readAsm1SlimFlowchart(
    data: Asm1SlimFlowchartsReadAsm1SlimFlowchartData,
  ): CancelablePromise<Asm1SlimFlowchartsReadAsm1SlimFlowchartResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm1slim-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Asm1Slim Flowchart
   * Update an ASM1Slim flowchart.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ASM1SlimFlowChartPublic Successful Response
   * @throws ApiError
   */
  public static updateAsm1SlimFlowchart(
    data: Asm1SlimFlowchartsUpdateAsm1SlimFlowchartData,
  ): CancelablePromise<Asm1SlimFlowchartsUpdateAsm1SlimFlowchartResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/asm1slim-flowcharts/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Asm1Slim Flowchart
   * Delete an ASM1Slim flowchart.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteAsm1SlimFlowchart(
    data: Asm1SlimFlowchartsDeleteAsm1SlimFlowchartData,
  ): CancelablePromise<Asm1SlimFlowchartsDeleteAsm1SlimFlowchartResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/asm1slim-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class Asm3Service {
  /**
   * Create Calculation Job
   * 创建ASM3计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM3JobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJob(
    data: Asm3CreateCalculationJobData,
  ): CancelablePromise<Asm3CreateCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm3/calculate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Calculation Job From Flowchart
   * 从流程图数据创建ASM3计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM3JobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJobFromFlowchart(
    data: Asm3CreateCalculationJobFromFlowchartData,
  ): CancelablePromise<Asm3CreateCalculationJobFromFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm3/calculate-from-flowchart",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Result Summary
   * 获取ASM3计算结果摘要
   * @param data The data for the request.
   * @param data.jobId
   * @returns MaterialBalanceResultSummary Successful Response
   * @throws ApiError
   */
  public static getCalculationResultSummary(
    data: Asm3GetCalculationResultSummaryData,
  ): CancelablePromise<Asm3GetCalculationResultSummaryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3/result/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Final Values
   * 获取ASM3计算的最终值
   * @param data The data for the request.
   * @param data.jobId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getCalculationFinalValues(
    data: Asm3GetCalculationFinalValuesData,
  ): CancelablePromise<Asm3GetCalculationFinalValuesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3/result/{job_id}/final-values",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Timeseries
   * 获取ASM3计算的时间序列数据
   * @param data The data for the request.
   * @param data.jobId
   * @param data.startTime 开始时间 (小时)
   * @param data.endTime 结束时间 (小时)
   * @param data.page 页码
   * @param data.pageSize 每页数据量
   * @param data.nodeIds 指定节点ID列表
   * @param data.edgeIds 指定边ID列表
   * @returns MaterialBalanceTimeSeriesResponse Successful Response
   * @throws ApiError
   */
  public static getCalculationTimeseries(
    data: Asm3GetCalculationTimeseriesData,
  ): CancelablePromise<Asm3GetCalculationTimeseriesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3/result/{job_id}/timeseries",
      path: {
        job_id: data.jobId,
      },
      query: {
        start_time: data.startTime,
        end_time: data.endTime,
        page: data.page,
        page_size: data.pageSize,
        node_ids: data.nodeIds,
        edge_ids: data.edgeIds,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Status
   * 获取ASM3计算任务状态
   * @param data The data for the request.
   * @param data.jobId
   * @returns ASM3JobPublic Successful Response
   * @throws ApiError
   */
  public static getCalculationStatus(
    data: Asm3GetCalculationStatusData,
  ): CancelablePromise<Asm3GetCalculationStatusResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3/status/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Validate Calculation Input
   * 验证ASM3计算输入数据
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MaterialBalanceValidationResponse Successful Response
   * @throws ApiError
   */
  public static validateCalculationInput(
    data: Asm3ValidateCalculationInputData,
  ): CancelablePromise<Asm3ValidateCalculationInputResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm3/validate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Calculation Jobs
   * 获取用户的ASM3计算任务列表
   * @param data The data for the request.
   * @param data.skip 跳过的记录数
   * @param data.limit 返回的记录数
   * @returns ASM3JobsPublic Successful Response
   * @throws ApiError
   */
  public static getUserCalculationJobs(
    data: Asm3GetUserCalculationJobsData = {},
  ): CancelablePromise<Asm3GetUserCalculationJobsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3/jobs",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Calculation Job
   * 删除ASM3计算任务
   * @param data The data for the request.
   * @param data.jobId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCalculationJob(
    data: Asm3DeleteCalculationJobData,
  ): CancelablePromise<Asm3DeleteCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/asm3/jobs/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Job Input Data
   * 获取ASM3计算任务的输入数据
   * @param data The data for the request.
   * @param data.jobId
   * @returns ASM3JobInputDataResponse Successful Response
   * @throws ApiError
   */
  public static getJobInputData(
    data: Asm3GetJobInputDataData,
  ): CancelablePromise<Asm3GetJobInputDataResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3/jobs/{job_id}/input-data",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class Asm3FlowchartsService {
  /**
   * Read Asm3 Flowcharts
   * Retrieve ASM3 flowcharts.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ASM3FlowChartsPublic Successful Response
   * @throws ApiError
   */
  public static readAsm3Flowcharts(
    data: Asm3FlowchartsReadAsm3FlowchartsData = {},
  ): CancelablePromise<Asm3FlowchartsReadAsm3FlowchartsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3-flowcharts/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Asm3 Flowchart
   * Create new ASM3 flowchart.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ASM3FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static createAsm3Flowchart(
    data: Asm3FlowchartsCreateAsm3FlowchartData,
  ): CancelablePromise<Asm3FlowchartsCreateAsm3FlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/asm3-flowcharts/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Asm3 Flowchart
   * Get ASM3 flowchart by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ASM3FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static readAsm3Flowchart(
    data: Asm3FlowchartsReadAsm3FlowchartData,
  ): CancelablePromise<Asm3FlowchartsReadAsm3FlowchartResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/asm3-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Asm3 Flowchart
   * Update an ASM3 flowchart.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ASM3FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static updateAsm3Flowchart(
    data: Asm3FlowchartsUpdateAsm3FlowchartData,
  ): CancelablePromise<Asm3FlowchartsUpdateAsm3FlowchartResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/asm3-flowcharts/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Asm3 Flowchart
   * Delete an ASM3 flowchart.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteAsm3Flowchart(
    data: Asm3FlowchartsDeleteAsm3FlowchartData,
  ): CancelablePromise<Asm3FlowchartsDeleteAsm3FlowchartResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/asm3-flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class DataAnalysisService {
  /**
   * Get Upload Policy
   * 获取前端文件上传策略（支持的扩展、MIME 类型与最大大小）。
   * 供前端展示与本地校验使用，确保与后端配置一致。
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getUploadPolicy(): CancelablePromise<DataAnalysisGetUploadPolicyResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/upload-policy",
    })
  }

  /**
   * Upload File
   * 上传数据文件
   * @param data The data for the request.
   * @param data.formData
   * @returns FileUploadResponse Successful Response
   * @throws ApiError
   */
  public static uploadFile(
    data: DataAnalysisUploadFileData,
  ): CancelablePromise<DataAnalysisUploadFileResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/data-analysis/files/upload",
      formData: data.formData,
      mediaType: "multipart/form-data",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Files
   * 获取用户的文件列表
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @param data.status
   * @returns FilesPublic Successful Response
   * @throws ApiError
   */
  public static getFiles(
    data: DataAnalysisGetFilesData = {},
  ): CancelablePromise<DataAnalysisGetFilesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/files",
      query: {
        skip: data.skip,
        limit: data.limit,
        status: data.status,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get File
   * 获取文件详细信息
   * @param data The data for the request.
   * @param data.fileId
   * @returns FileDetail Successful Response
   * @throws ApiError
   */
  public static getFile(
    data: DataAnalysisGetFileData,
  ): CancelablePromise<DataAnalysisGetFileResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/files/{file_id}",
      path: {
        file_id: data.fileId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete File Endpoint
   * 删除文件
   * @param data The data for the request.
   * @param data.fileId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteFileEndpoint(
    data: DataAnalysisDeleteFileEndpointData,
  ): CancelablePromise<DataAnalysisDeleteFileEndpointResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/data-analysis/files/{file_id}",
      path: {
        file_id: data.fileId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get File Schema
   * 获取文件Schema（列名与dtype、总行数、可选编码信息）。并在缺失时回填到file_metadata中
   * @param data The data for the request.
   * @param data.fileId
   * @returns FileSchema Successful Response
   * @throws ApiError
   */
  public static getFileSchema(
    data: DataAnalysisGetFileSchemaData,
  ): CancelablePromise<DataAnalysisGetFileSchemaResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/files/{file_id}/schema",
      path: {
        file_id: data.fileId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Preview File
   * 分页预览文件数据，支持单列排序
   * @param data The data for the request.
   * @param data.fileId
   * @param data.skip
   * @param data.limit
   * @param data.sortBy
   * @param data.order
   * @returns DataPreview Successful Response
   * @throws ApiError
   */
  public static previewFile(
    data: DataAnalysisPreviewFileData,
  ): CancelablePromise<DataAnalysisPreviewFileResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/files/{file_id}/preview",
      path: {
        file_id: data.fileId,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
        sort_by: data.sortBy,
        order: data.order,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Basic Stats
   * 返回基础统计（shape、dtypes、null_counts、类型列分组）
   * @param data The data for the request.
   * @param data.fileId
   * @returns BasicStats Successful Response
   * @throws ApiError
   */
  public static getBasicStats(
    data: DataAnalysisGetBasicStatsData,
  ): CancelablePromise<DataAnalysisGetBasicStatsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/files/{file_id}/basic-stats",
      path: {
        file_id: data.fileId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Analysis Task
   * 创建分析任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns AnalysisTaskPublic Successful Response
   * @throws ApiError
   */
  public static createAnalysisTask(
    data: DataAnalysisCreateAnalysisTaskData,
  ): CancelablePromise<DataAnalysisCreateAnalysisTaskResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/data-analysis/tasks",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Analysis Tasks
   * 获取分析任务列表
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @param data.status
   * @param data.analysisType
   * @param data.xTimezone
   * @returns AnalysisTasksPublic Successful Response
   * @throws ApiError
   */
  public static getAnalysisTasks(
    data: DataAnalysisGetAnalysisTasksData = {},
  ): CancelablePromise<DataAnalysisGetAnalysisTasksResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/tasks",
      headers: {
        "X-Timezone": data.xTimezone,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
        status: data.status,
        analysis_type: data.analysisType,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Analysis Task
   * 获取分析任务详细信息
   * @param data The data for the request.
   * @param data.taskId
   * @returns AnalysisTaskDetail Successful Response
   * @throws ApiError
   */
  public static getAnalysisTask(
    data: DataAnalysisGetAnalysisTaskData,
  ): CancelablePromise<DataAnalysisGetAnalysisTaskResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/tasks/{task_id}",
      path: {
        task_id: data.taskId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Analysis Task
   * 更新分析任务
   * @param data The data for the request.
   * @param data.taskId
   * @param data.requestBody
   * @returns AnalysisTaskPublic Successful Response
   * @throws ApiError
   */
  public static updateAnalysisTask(
    data: DataAnalysisUpdateAnalysisTaskData,
  ): CancelablePromise<DataAnalysisUpdateAnalysisTaskResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/data-analysis/tasks/{task_id}",
      path: {
        task_id: data.taskId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Analysis Task
   * 删除分析任务
   * @param data The data for the request.
   * @param data.taskId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteAnalysisTask(
    data: DataAnalysisDeleteAnalysisTaskData,
  ): CancelablePromise<DataAnalysisDeleteAnalysisTaskResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/data-analysis/tasks/{task_id}",
      path: {
        task_id: data.taskId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Task Progress Endpoint
   * 获取任务进度
   * @param data The data for the request.
   * @param data.taskId
   * @returns TaskProgressResponse Successful Response
   * @throws ApiError
   */
  public static getTaskProgressEndpoint(
    data: DataAnalysisGetTaskProgressEndpointData,
  ): CancelablePromise<DataAnalysisGetTaskProgressEndpointResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/tasks/{task_id}/progress",
      path: {
        task_id: data.taskId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Cancel Analysis Task
   * 取消分析任务
   * @param data The data for the request.
   * @param data.taskId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static cancelAnalysisTask(
    data: DataAnalysisCancelAnalysisTaskData,
  ): CancelablePromise<DataAnalysisCancelAnalysisTaskResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/data-analysis/tasks/{task_id}/cancel",
      path: {
        task_id: data.taskId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Task Results
   * 获取任务结果列表
   * @param data The data for the request.
   * @param data.taskId
   * @param data.skip
   * @param data.limit
   * @returns AnalysisResultsDetail Successful Response
   * @throws ApiError
   */
  public static getTaskResults(
    data: DataAnalysisGetTaskResultsData,
  ): CancelablePromise<DataAnalysisGetTaskResultsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/tasks/{task_id}/results",
      path: {
        task_id: data.taskId,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Result
   * 获取单个结果详情
   * @param data The data for the request.
   * @param data.resultId
   * @returns AnalysisResultPublic Successful Response
   * @throws ApiError
   */
  public static getResult(
    data: DataAnalysisGetResultData,
  ): CancelablePromise<DataAnalysisGetResultResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/results/{result_id}",
      path: {
        result_id: data.resultId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Export Result
   * 导出分析结果
   * @param data The data for the request.
   * @param data.resultId
   * @param data.requestBody
   * @returns ExportResponse Successful Response
   * @throws ApiError
   */
  public static exportResult(
    data: DataAnalysisExportResultData,
  ): CancelablePromise<DataAnalysisExportResultResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/data-analysis/results/{result_id}/export",
      path: {
        result_id: data.resultId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Download Export
   * 下载导出的文件
   * @param data The data for the request.
   * @param data.filename
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static downloadExport(
    data: DataAnalysisDownloadExportData,
  ): CancelablePromise<DataAnalysisDownloadExportResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/exports/{filename}",
      path: {
        filename: data.filename,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Validate Analysis Config
   * 验证分析配置
   * @param data The data for the request.
   * @param data.requestBody
   * @returns AnalysisValidationResponse Successful Response
   * @throws ApiError
   */
  public static validateAnalysisConfig(
    data: DataAnalysisValidateAnalysisConfigData,
  ): CancelablePromise<DataAnalysisValidateAnalysisConfigResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/data-analysis/validate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Analysis Stats
   * 获取分析统计信息
   * @returns AnalysisStats Successful Response
   * @throws ApiError
   */
  public static getAnalysisStats(): CancelablePromise<DataAnalysisGetAnalysisStatsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/stats",
    })
  }

  /**
   * Get System Health
   * 获取系统健康状态
   * @returns SystemHealth Successful Response
   * @throws ApiError
   */
  public static getSystemHealth(): CancelablePromise<DataAnalysisGetSystemHealthResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/health",
    })
  }

  /**
   * Get Task Status Quick
   * 快速获取任务状态（仅从缓存）
   * @param data The data for the request.
   * @param data.taskId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getTaskStatusQuick(
    data: DataAnalysisGetTaskStatusQuickData,
  ): CancelablePromise<DataAnalysisGetTaskStatusQuickResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/tasks/{task_id}/status-quick",
      path: {
        task_id: data.taskId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Task Results Quick
   * 从缓存获取任务结果
   * @param data The data for the request.
   * @param data.taskId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getTaskResultsQuick(
    data: DataAnalysisGetTaskResultsQuickData,
  ): CancelablePromise<DataAnalysisGetTaskResultsQuickResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/data-analysis/tasks/{task_id}/results-quick",
      path: {
        task_id: data.taskId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Upload File Alias
   * 上传数据文件 (简化端点别名)
   *
   * 这是 /files/upload 的别名，提供更简洁的API路径
   * @param data The data for the request.
   * @param data.formData
   * @returns FileUploadResponse Successful Response
   * @throws ApiError
   */
  public static uploadFileAlias(
    data: DataAnalysisUploadFileAliasData,
  ): CancelablePromise<DataAnalysisUploadFileAliasResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/data-analysis/upload",
      formData: data.formData,
      mediaType: "multipart/form-data",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Analysis Task Alias
   * 创建分析任务 (简化端点别名)
   *
   * 这是 /tasks 的别名，提供更简洁的API路径
   * @param data The data for the request.
   * @param data.requestBody
   * @returns AnalysisTaskPublic Successful Response
   * @throws ApiError
   */
  public static createAnalysisTaskAlias(
    data: DataAnalysisCreateAnalysisTaskAliasData,
  ): CancelablePromise<DataAnalysisCreateAnalysisTaskAliasResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/data-analysis/analyze",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class FlowchartsService {
  /**
   * Read Flowcharts
   * Retrieve flowcharts.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns FlowChartsPublic Successful Response
   * @throws ApiError
   */
  public static readFlowcharts(
    data: FlowchartsReadFlowchartsData = {},
  ): CancelablePromise<FlowchartsReadFlowchartsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/flowcharts/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Flowchart
   * Create new flowchart.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static createFlowchart(
    data: FlowchartsCreateFlowchartData,
  ): CancelablePromise<FlowchartsCreateFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/flowcharts/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Flowchart
   * Get flowchart by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static readFlowchart(
    data: FlowchartsReadFlowchartData,
  ): CancelablePromise<FlowchartsReadFlowchartResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Flowchart
   * Update a flowchart.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns FlowChartPublic Successful Response
   * @throws ApiError
   */
  public static updateFlowchart(
    data: FlowchartsUpdateFlowchartData,
  ): CancelablePromise<FlowchartsUpdateFlowchartResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/flowcharts/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Flowchart
   * Delete a flowchart.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteFlowchart(
    data: FlowchartsDeleteFlowchartData,
  ): CancelablePromise<FlowchartsDeleteFlowchartResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/flowcharts/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ItemsService {
  /**
   * Read Items
   * Retrieve items.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ItemsPublic Successful Response
   * @throws ApiError
   */
  public static readItems(
    data: ItemsReadItemsData = {},
  ): CancelablePromise<ItemsReadItemsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Item
   * Create new item.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static createItem(
    data: ItemsCreateItemData,
  ): CancelablePromise<ItemsCreateItemResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/items/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Item
   * Get item by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static readItem(
    data: ItemsReadItemData,
  ): CancelablePromise<ItemsReadItemResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Item
   * Update an item.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static updateItem(
    data: ItemsUpdateItemData,
  ): CancelablePromise<ItemsUpdateItemResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Item
   * Delete an item.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteItem(
    data: ItemsDeleteItemData,
  ): CancelablePromise<ItemsDeleteItemResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData,
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<LoginTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/test-token",
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData,
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData,
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: LoginRecoverPasswordHtmlContentData,
  ): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class MaterialBalanceService {
  /**
   * Create Calculation Job
   * 创建物料平衡计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MaterialBalanceJobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJob(
    data: MaterialBalanceCreateCalculationJobData,
  ): CancelablePromise<MaterialBalanceCreateCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/material-balance/calculate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Calculation Job From Flowchart
   * 从流程图数据创建物料平衡计算任务
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MaterialBalanceJobPublic Successful Response
   * @throws ApiError
   */
  public static createCalculationJobFromFlowchart(
    data: MaterialBalanceCreateCalculationJobFromFlowchartData,
  ): CancelablePromise<MaterialBalanceCreateCalculationJobFromFlowchartResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/material-balance/calculate-from-flowchart",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Result Summary
   * 获取计算结果摘要
   * @param data The data for the request.
   * @param data.jobId
   * @returns MaterialBalanceResultSummary Successful Response
   * @throws ApiError
   */
  public static getCalculationResultSummary(
    data: MaterialBalanceGetCalculationResultSummaryData,
  ): CancelablePromise<MaterialBalanceGetCalculationResultSummaryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/material-balance/result/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Final Values
   * 获取计算结果中数组的最后一位数据（最终状态）
   * @param data The data for the request.
   * @param data.jobId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getCalculationFinalValues(
    data: MaterialBalanceGetCalculationFinalValuesData,
  ): CancelablePromise<MaterialBalanceGetCalculationFinalValuesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/material-balance/result/{job_id}/final-values",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Timeseries
   * 分页获取时间序列数据
   * @param data The data for the request.
   * @param data.jobId
   * @param data.startTime 开始时间 (小时)
   * @param data.endTime 结束时间 (小时)
   * @param data.page 页码
   * @param data.pageSize 每页数据量
   * @param data.nodeIds 指定节点ID列表
   * @param data.edgeIds 指定边ID列表
   * @returns MaterialBalanceTimeSeriesResponse Successful Response
   * @throws ApiError
   */
  public static getCalculationTimeseries(
    data: MaterialBalanceGetCalculationTimeseriesData,
  ): CancelablePromise<MaterialBalanceGetCalculationTimeseriesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/material-balance/result/{job_id}/timeseries",
      path: {
        job_id: data.jobId,
      },
      query: {
        start_time: data.startTime,
        end_time: data.endTime,
        page: data.page,
        page_size: data.pageSize,
        node_ids: data.nodeIds,
        edge_ids: data.edgeIds,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Calculation Status
   * 查询计算状态
   * @param data The data for the request.
   * @param data.jobId
   * @returns MaterialBalanceJobPublic Successful Response
   * @throws ApiError
   */
  public static getCalculationStatus(
    data: MaterialBalanceGetCalculationStatusData,
  ): CancelablePromise<MaterialBalanceGetCalculationStatusResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/material-balance/status/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Validate Calculation Input
   * 验证输入参数
   * @param data The data for the request.
   * @param data.requestBody
   * @returns MaterialBalanceValidationResponse Successful Response
   * @throws ApiError
   */
  public static validateCalculationInput(
    data: MaterialBalanceValidateCalculationInputData,
  ): CancelablePromise<MaterialBalanceValidateCalculationInputResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/material-balance/validate",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get User Calculation Jobs
   * 获取用户的计算任务列表
   * @param data The data for the request.
   * @param data.skip 跳过的记录数
   * @param data.limit 返回的记录数
   * @returns MaterialBalanceJobsPublic Successful Response
   * @throws ApiError
   */
  public static getUserCalculationJobs(
    data: MaterialBalanceGetUserCalculationJobsData = {},
  ): CancelablePromise<MaterialBalanceGetUserCalculationJobsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/material-balance/jobs",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Calculation Job
   * 删除计算任务
   * @param data The data for the request.
   * @param data.jobId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCalculationJob(
    data: MaterialBalanceDeleteCalculationJobData,
  ): CancelablePromise<MaterialBalanceDeleteCalculationJobResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/material-balance/jobs/{job_id}",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Job Input Data
   * 获取计算任务的输入数据
   * @param data The data for the request.
   * @param data.jobId
   * @returns MaterialBalanceJobInputDataResponse Successful Response
   * @throws ApiError
   */
  public static getJobInputData(
    data: MaterialBalanceGetJobInputDataData,
  ): CancelablePromise<MaterialBalanceGetJobInputDataResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/material-balance/jobs/{job_id}/input-data",
      path: {
        job_id: data.jobId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: PrivateCreateUserData,
  ): CancelablePromise<PrivateCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/private/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class SimpleWebsocketService {
  /**
   * Get Task Connections
   * 获取指定任务的WebSocket连接信息
   *
   * Args:
   * task_id: 任务ID
   *
   * Returns:
   * 连接信息
   * @param data The data for the request.
   * @param data.taskId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getTaskConnections(
    data: SimpleWebsocketGetTaskConnectionsData,
  ): CancelablePromise<SimpleWebsocketGetTaskConnectionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/simple-ws/connections/{task_id}",
      path: {
        task_id: data.taskId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Broadcast Message
   * 向指定任务的所有连接广播消息
   *
   * Args:
   * task_id: 任务ID
   * message: 要广播的消息
   *
   * Returns:
   * 广播结果
   * @param data The data for the request.
   * @param data.taskId
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static broadcastMessage(
    data: SimpleWebsocketBroadcastMessageData,
  ): CancelablePromise<SimpleWebsocketBroadcastMessageResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/simple-ws/broadcast/{task_id}",
      path: {
        task_id: data.taskId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Websocket Health
   * WebSocket服务健康检查
   *
   * Returns:
   * 健康状态
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static websocketHealth(): CancelablePromise<SimpleWebsocketWebsocketHealthResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/simple-ws/health",
    })
  }
}

export class StatsService {
  /**
   * Get Dashboard Stats
   * 获取超级用户dashboard统计数据
   * 只有超级用户可以访问此接口
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getDashboardStats(): CancelablePromise<StatsGetDashboardStatsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/stats/dashboard",
    })
  }

  /**
   * Get User Stats
   * 获取详细的用户统计信息
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getUserStats(): CancelablePromise<StatsGetUserStatsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/stats/users",
    })
  }
}

export class UsersService {
  /**
   * Read Users
   * Retrieve users.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: UsersReadUsersData = {},
  ): CancelablePromise<UsersReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create User
   * Create new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: UsersCreateUserData,
  ): CancelablePromise<UsersCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User Me
   * Get current user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * Delete own user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * Update own user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData,
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * Update own password.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UsersUpdatePasswordMeData,
  ): CancelablePromise<UsersUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register User
   * Create new user without the need to be logged in.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: UsersRegisterUserData,
  ): CancelablePromise<UsersRegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * Get a specific user by id.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: UsersReadUserByIdData,
  ): CancelablePromise<UsersReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User
   * Update a user.
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UsersUpdateUserData,
  ): CancelablePromise<UsersUpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User
   * Delete a user.
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: UsersDeleteUserData,
  ): CancelablePromise<UsersDeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: UtilsTestEmailData,
  ): CancelablePromise<UtilsTestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/test-email/",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Health Check
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    })
  }
}

export class WebsocketService {
  /**
   * Get Websocket Stats
   * 获取WebSocket连接统计信息
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getWebsocketStats(): CancelablePromise<WebsocketGetWebsocketStatsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/ws/stats",
    })
  }

  /**
   * Test Send Progress
   * 手动发送进度更新（测试用）
   * @param data The data for the request.
   * @param data.taskId
   * @param data.progress
   * @param data.message
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static testSendProgress(
    data: WebsocketTestSendProgressData,
  ): CancelablePromise<WebsocketTestSendProgressResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/ws/test/send-progress/{task_id}",
      path: {
        task_id: data.taskId,
      },
      query: {
        progress: data.progress,
        message: data.message,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Send Completion
   * 手动发送任务完成消息（测试用）
   * @param data The data for the request.
   * @param data.taskId
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static testSendCompletion(
    data: WebsocketTestSendCompletionData,
  ): CancelablePromise<WebsocketTestSendCompletionResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/ws/test/send-completion/{task_id}",
      path: {
        task_id: data.taskId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}
