// This file is auto-generated by @hey-api/openapi-ts

/**
 * 分析配置
 */
export type AnalysisConfig = {
  analysis_type: AnalysisType
  /**
   * 分析参数
   */
  parameters?: {
    [key: string]: unknown
  }
  /**
   * 输出格式
   */
  output_formats?: Array<ExportFormat>
  /**
   * 管道类型
   */
  pipeline_type?: number | null
}

/**
 * 分析进度
 */
export type AnalysisProgress = {
  /**
   * 当前步骤
   */
  current_step: string
  /**
   * 总步骤数
   */
  total_steps: number
  /**
   * 已完成步骤数
   */
  completed_steps: number
  /**
   * 进度百分比
   */
  progress_percentage: number
  /**
   * 预估剩余时间（秒）
   */
  estimated_remaining_time?: number | null
}

/**
 * 分析结果详细信息
 */
export type AnalysisResultDetail = {
  /**
   * 结果ID
   */
  result_id: string
  /**
   * 任务ID
   */
  task_id: string
  /**
   * 结果类型
   */
  result_type: string
  /**
   * 创建时间
   */
  created_at: string
  /**
   * 分析结果数据
   */
  result_data: {
    [key: string]: unknown
  }
  /**
   * 结果元数据
   */
  result_metadata?: {
    [key: string]: unknown
  }
  /**
   * 结果文件路径
   */
  file_path?: string | null
}

/**
 * 分析结果公开信息
 */
export type AnalysisResultPublic = {
  /**
   * 结果ID
   */
  result_id: string
  /**
   * 任务ID
   */
  task_id: string
  /**
   * 结果类型
   */
  result_type: string
  /**
   * 创建时间
   */
  created_at: string
}

/**
 * 分析结果详细列表响应
 */
export type AnalysisResultsDetail = {
  /**
   * 结果详细列表
   */
  data: Array<AnalysisResultDetail>
  /**
   * 总数量
   */
  count: number
}

/**
 * 分析统计信息
 */
export type AnalysisStats = {
  /**
   * 总文件数
   */
  total_files: number
  /**
   * 总任务数
   */
  total_tasks: number
  /**
   * 已完成任务数
   */
  completed_tasks: number
  /**
   * 失败任务数
   */
  failed_tasks: number
  /**
   * 总存储使用量（字节）
   */
  total_storage_used: number
}

/**
 * 创建分析任务请求
 */
export type AnalysisTaskCreate = {
  /**
   * 文件ID
   */
  file_id: string
  /**
   * 任务名称
   */
  task_name: string
  /**
   * 任务描述
   */
  description?: string | null
  config: AnalysisConfig
}

/**
 * 分析任务详细信息
 */
export type AnalysisTaskDetail = {
  /**
   * 任务ID
   */
  task_id: string
  /**
   * 任务名称
   */
  task_name: string
  /**
   * 任务描述
   */
  description: string | null
  /**
   * 任务状态
   */
  status: AnalysisTaskStatus
  /**
   * 任务进度
   */
  progress: AnalysisProgress
  /**
   * 创建时间
   */
  created_at: string
  /**
   * 更新时间
   */
  updated_at: string
  /**
   * 开始时间
   */
  started_at: string | null
  /**
   * 完成时间
   */
  completed_at: string | null
  analysis_type: AnalysisType
  /**
   * 分析参数
   */
  parameters: {
    [key: string]: unknown
  }
  /**
   * 文件名
   */
  filename: string | null
  /**
   * 原始文件名
   */
  original_filename: string | null
  /**
   * 文件ID
   */
  file_id: string
  config: AnalysisConfig
  /**
   * 错误信息
   */
  error_message: string | null
  /**
   * 文件信息
   */
  file_info: FileMetadata
}

/**
 * 分析任务公开信息
 */
export type AnalysisTaskPublic = {
  /**
   * 任务ID
   */
  task_id: string
  /**
   * 任务名称
   */
  task_name: string
  /**
   * 任务描述
   */
  description: string | null
  /**
   * 任务状态
   */
  status: AnalysisTaskStatus
  /**
   * 任务进度
   */
  progress: AnalysisProgress
  /**
   * 创建时间
   */
  created_at: string
  /**
   * 更新时间
   */
  updated_at: string
  /**
   * 开始时间
   */
  started_at: string | null
  /**
   * 完成时间
   */
  completed_at: string | null
  analysis_type: AnalysisType
  /**
   * 分析参数
   */
  parameters: {
    [key: string]: unknown
  }
  /**
   * 文件名
   */
  filename: string | null
  /**
   * 原始文件名
   */
  original_filename: string | null
  /**
   * 文件ID
   */
  file_id: string
}

/**
 * 分析任务列表响应
 */
export type AnalysisTasksPublic = {
  /**
   * 任务列表
   */
  data: Array<AnalysisTaskPublic>
  /**
   * 总数量
   */
  count: number
}

/**
 * 分析任务状态
 */
export type AnalysisTaskStatus =
  | "pending"
  | "running"
  | "completed"
  | "failed"
  | "cancelled"

/**
 * 更新分析任务请求
 */
export type AnalysisTaskUpdate = {
  /**
   * 任务名称
   */
  task_name?: string | null
  /**
   * 任务描述
   */
  description?: string | null
  /**
   * 分析配置
   */
  config?: AnalysisConfig | null
}

/**
 * 分析类型
 */
export type AnalysisType =
  | "eda"
  | "grouping"
  | "quality_control"
  | "timeseries"
  | "automl"
  | "custom"

/**
 * 分析配置验证请求
 */
export type AnalysisValidationRequest = {
  /**
   * 文件ID
   */
  file_id: string
  config: AnalysisConfig
}

/**
 * 分析配置验证响应
 */
export type AnalysisValidationResponse = {
  /**
   * 配置是否有效
   */
  is_valid: boolean
  /**
   * 错误列表
   */
  errors?: Array<string>
  /**
   * 警告列表
   */
  warnings?: Array<string>
  /**
   * 预估执行时间（秒）
   */
  estimated_time: number | null
  /**
   * 预估内存使用（MB）
   */
  estimated_memory: number | null
}

/**
 * 创建ASM1流程图请求
 */
export type ASM1FlowChartCreate = {
  name: string
  description?: string | null
  /**
   * 完整的流程图数据
   */
  flow_data: {
    [key: string]: unknown
  }
}

/**
 * ASM1流程图公开信息
 */
export type ASM1FlowChartPublic = {
  name: string
  description?: string | null
  id: string
  owner_id: string
  created_at: string
  updated_at: string
  flow_data: {
    [key: string]: unknown
  }
}

/**
 * ASM1流程图列表
 */
export type ASM1FlowChartsPublic = {
  data?: Array<ASM1FlowChartPublic>
  count: number
}

/**
 * 更新ASM1流程图请求
 */
export type ASM1FlowChartUpdate = {
  name?: string | null
  description?: string | null
  /**
   * 完整的流程图数据
   */
  flow_data?: {
    [key: string]: unknown
  } | null
}

/**
 * ASM1任务输入数据响应
 */
export type ASM1JobInputDataResponse = {
  /**
   * 计算任务ID
   */
  job_id: string
  /**
   * 输入数据
   */
  input_data: {
    [key: string]: unknown
  }
  /**
   * 计算结果数据
   */
  result_data: {
    [key: string]: unknown
  }
  /**
   * 任务状态
   */
  status: MaterialBalanceJobStatus
}

/**
 * ASM1任务公开信息
 */
export type ASM1JobPublic = {
  id: string
  job_id: string
  job_name: string
  status: MaterialBalanceJobStatus
  created_at: string
  started_at: string | null
  completed_at: string | null
  error_message: string | null
  /**
   * 计算结果数据
   */
  result_data?: {
    [key: string]: unknown
  } | null
}

/**
 * ASM1任务列表
 */
export type ASM1JobsPublic = {
  data: Array<ASM1JobPublic>
  count: number
}

/**
 * 创建ASM1slim流程图请求
 */
export type ASM1SlimFlowChartCreate = {
  name: string
  description?: string | null
  /**
   * 完整的流程图数据
   */
  flow_data: {
    [key: string]: unknown
  }
}

/**
 * ASM1slim流程图公开信息
 */
export type ASM1SlimFlowChartPublic = {
  name: string
  description?: string | null
  id: string
  owner_id: string
  created_at: string
  updated_at: string
  flow_data: {
    [key: string]: unknown
  }
}

/**
 * ASM1slim流程图列表
 */
export type ASM1SlimFlowChartsPublic = {
  data: Array<ASM1SlimFlowChartPublic>
  count: number
}

/**
 * 更新ASM1slim流程图请求
 */
export type ASM1SlimFlowChartUpdate = {
  name?: string | null
  description?: string | null
  /**
   * 完整的流程图数据
   */
  flow_data?: {
    [key: string]: unknown
  } | null
}

/**
 * ASM1slim任务输入数据响应
 */
export type ASM1SlimJobInputDataResponse = {
  /**
   * 计算任务ID
   */
  job_id: string
  /**
   * 输入数据
   */
  input_data: {
    [key: string]: unknown
  }
  /**
   * 计算结果数据
   */
  result_data: {
    [key: string]: unknown
  }
  /**
   * 任务状态
   */
  status: MaterialBalanceJobStatus
}

/**
 * ASM1slim任务公开信息
 */
export type ASM1SlimJobPublic = {
  id: string
  job_id: string
  job_name: string
  status: MaterialBalanceJobStatus
  created_at: string
  started_at: string | null
  completed_at: string | null
  error_message: string | null
  /**
   * 计算结果数据
   */
  result_data?: {
    [key: string]: unknown
  } | null
}

/**
 * ASM1slim任务列表
 */
export type ASM1SlimJobsPublic = {
  data: Array<ASM1SlimJobPublic>
  count: number
}

/**
 * ASM3流程图创建模型
 */
export type ASM3FlowChartCreate = {
  name: string
  description?: string | null
  /**
   * 完整的流程图数据
   */
  flow_data: {
    [key: string]: unknown
  }
}

/**
 * ASM3流程图公开模型
 */
export type ASM3FlowChartPublic = {
  name: string
  description?: string | null
  id: string
  owner_id: string
  created_at: string
  updated_at: string
  flow_data: {
    [key: string]: unknown
  }
}

/**
 * ASM3流程图列表
 */
export type ASM3FlowChartsPublic = {
  data?: Array<ASM3FlowChartPublic>
  count: number
}

/**
 * ASM3流程图更新模型
 */
export type ASM3FlowChartUpdate = {
  name?: string | null
  description?: string | null
  /**
   * 完整的流程图数据
   */
  flow_data?: {
    [key: string]: unknown
  } | null
}

/**
 * ASM3任务输入数据响应
 */
export type ASM3JobInputDataResponse = {
  /**
   * 计算任务ID
   */
  job_id: string
  /**
   * 输入数据
   */
  input_data: {
    [key: string]: unknown
  }
  /**
   * 计算结果数据
   */
  result_data: {
    [key: string]: unknown
  }
  /**
   * 任务状态
   */
  status: MaterialBalanceJobStatus
}

/**
 * ASM3任务公开模型
 */
export type ASM3JobPublic = {
  id: string
  job_id: string
  job_name: string
  status: MaterialBalanceJobStatus
  created_at: string
  started_at: string | null
  completed_at: string | null
  error_message: string | null
  /**
   * 计算结果数据
   */
  result_data?: {
    [key: string]: unknown
  } | null
}

/**
 * ASM3任务列表
 */
export type ASM3JobsPublic = {
  data: Array<ASM3JobPublic>
  count: number
}

/**
 * 基础统计信息（用于左栏展示）
 */
export type BasicStats = {
  /**
   * 行数
   */
  shape_rows: number
  /**
   * 列数
   */
  shape_cols: number
  /**
   * 各列dtype
   */
  dtypes?: {
    [key: string]: string
  }
  /**
   * 各列空值计数
   */
  null_counts?: {
    [key: string]: number
  }
  /**
   * 数值型列
   */
  numeric_columns?: Array<string>
  /**
   * 分类型列
   */
  categorical_columns?: Array<string>
  /**
   * 时间列
   */
  datetime_columns?: Array<string>
  /**
   * 布尔列
   */
  boolean_columns?: Array<string>
}

export type Body_data_analysis_upload_file = {
  file: Blob | File
}

export type Body_data_analysis_upload_file_alias = {
  file: Blob | File
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

/**
 * 计算参数
 */
export type CalculationParameters = {
  /**
   * 模拟时间 (小时)
   */
  hours?: number
  /**
   * 每小时步数
   */
  steps_per_hour?: number
  solver_method?: SolverMethod
  /**
   * 求解精度
   */
  tolerance?: number
  /**
   * 最大迭代次数
   */
  max_iterations?: number
  /**
   * 最大内存使用 (MB)
   */
  max_memory_mb?: number
  /**
   * 采样间隔 (小时)，用于数据存储优化
   */
  sampling_interval_hours?: number | null
}

/**
 * 数据预览响应（分页）
 */
export type DataPreview = {
  /**
   * 列名列表
   */
  columns: Array<string>
  /**
   * 数据总行数
   */
  total_rows: number
  /**
   * 当前页数据记录
   */
  rows: Array<{
    [key: string]: unknown
  }>
}

/**
 * 流程图边数据
 */
export type EdgeData = {
  /**
   * 边唯一标识符
   */
  edge_id: string
  /**
   * 源节点ID
   */
  source_node_id: string
  /**
   * 目标节点ID
   */
  target_node_id: string
  /**
   * 流量 (m³/h)
   */
  flow_rate: number
  /**
   * 浓度比例因子
   */
  concentration_factor_a?: Array<number>
  /**
   * 浓度偏移因子
   */
  concentration_factor_b?: Array<number>
}

/**
 * 导出格式
 */
export type ExportFormat = "json" | "excel" | "html" | "markdown" | "pdf"

/**
 * 导出请求
 */
export type ExportRequest = {
  /**
   * 任务ID
   */
  task_id: string
  format: ExportFormat
  /**
   * 是否包含原始数据
   */
  include_raw_data?: boolean
  /**
   * 是否包含可视化
   */
  include_visualizations?: boolean
}

/**
 * 导出响应
 */
export type ExportResponse = {
  /**
   * 导出ID
   */
  export_id: string
  /**
   * 下载链接
   */
  download_url: string
  /**
   * 链接过期时间
   */
  expires_at: string
  /**
   * 文件大小
   */
  file_size: number | null
}

/**
 * 文件详细信息
 */
export type FileDetail = {
  /**
   * 文件ID
   */
  file_id: string
  /**
   * 文件名
   */
  filename: string
  /**
   * 原始文件名
   */
  original_filename: string
  /**
   * 文件大小
   */
  file_size: number
  /**
   * MIME类型
   */
  mime_type: string
  status: FileStatus
  /**
   * 创建时间
   */
  created_at: string
  /**
   * 更新时间
   */
  updated_at: string
  file_metadata_info: FileMetadata
}

/**
 * 文件元数据
 */
export type FileMetadata = {
  /**
   * 文件名
   */
  filename: string
  /**
   * 原始文件名
   */
  original_filename: string
  /**
   * 文件大小（字节）
   */
  file_size: number
  /**
   * MIME类型
   */
  mime_type: string
  /**
   * 文件编码
   */
  encoding?: string | null
  /**
   * 数据列名
   */
  columns?: Array<string> | null
  /**
   * 数据行数
   */
  rows_count?: number | null
  /**
   * 文件哈希值
   */
  file_hash?: string | null
}

/**
 * 文件公开信息
 */
export type FilePublic = {
  /**
   * 文件ID
   */
  file_id: string
  /**
   * 文件名
   */
  filename: string
  /**
   * 原始文件名
   */
  original_filename: string
  /**
   * 文件大小
   */
  file_size: number
  /**
   * MIME类型
   */
  mime_type: string
  status: FileStatus
  /**
   * 创建时间
   */
  created_at: string
  /**
   * 更新时间
   */
  updated_at: string
}

/**
 * 文件的Schema信息（用于左栏预览/配置）
 */
export type FileSchema = {
  /**
   * 列定义列表
   */
  columns: Array<FileSchemaColumn>
  /**
   * 数据总行数
   */
  rows_count: number
  /**
   * 文本文件编码（如可识别）
   */
  encoding?: string | null
  /**
   * 建议的预览默认行数
   */
  sample_rows?: number
}

/**
 * 文件列的名称与类型描述
 */
export type FileSchemaColumn = {
  /**
   * 列名
   */
  name: string
  /**
   * Pandas 推断的dtype
   */
  dtype: string
}

/**
 * 文件列表响应
 */
export type FilesPublic = {
  /**
   * 文件列表
   */
  data: Array<FilePublic>
  /**
   * 总数量
   */
  count: number
}

/**
 * 文件状态
 */
export type FileStatus =
  | "uploading"
  | "uploaded"
  | "processing"
  | "processed"
  | "failed"
  | "deleted"

/**
 * 文件上传响应
 */
export type FileUploadResponse = {
  /**
   * 文件ID
   */
  file_id: string
  /**
   * 文件名
   */
  filename: string
  status: FileStatus
}

export type FlowChartCreate = {
  name: string
  description?: string | null
  /**
   * Complete flow chart data including nodes, edges, and configurations
   */
  flow_data: {
    [key: string]: unknown
  }
}

export type FlowChartPublic = {
  name: string
  description?: string | null
  id: string
  owner_id: string
  created_at: string
  updated_at: string
  flow_data: {
    [key: string]: unknown
  }
}

export type FlowChartsPublic = {
  data: Array<FlowChartPublic>
  count: number
}

export type FlowChartUpdate = {
  name?: string | null
  description?: string | null
  /**
   * Complete flow chart data including nodes, edges, and configurations
   */
  flow_data?: {
    [key: string]: unknown
  } | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

/**
 * 物料平衡计算输入数据模型
 */
export type MaterialBalanceInput = {
  /**
   * 节点数据列表
   */
  nodes: Array<NodeData>
  /**
   * 边数据列表
   */
  edges: Array<EdgeData>
  parameters: CalculationParameters
  /**
   * 原始流程图数据，用于保留原始参数名称
   */
  original_flowchart_data?: {
    [key: string]: unknown
  } | null
}

/**
 * 物料平衡任务输入数据响应
 */
export type MaterialBalanceJobInputDataResponse = {
  /**
   * 计算任务ID
   */
  job_id: string
  /**
   * 输入数据
   */
  input_data: {
    [key: string]: unknown
  }
  /**
   * 计算结果数据
   */
  result_data: {
    [key: string]: unknown
  }
  /**
   * 任务状态
   */
  status: MaterialBalanceJobStatus
}

/**
 * 物料平衡任务公开信息
 */
export type MaterialBalanceJobPublic = {
  id: string
  job_id: string
  job_name: string
  status: MaterialBalanceJobStatus
  created_at: string
  started_at: string | null
  completed_at: string | null
  error_message: string | null
}

/**
 * 物料平衡任务列表
 */
export type MaterialBalanceJobsPublic = {
  data: Array<MaterialBalanceJobPublic>
  count: number
}

/**
 * 物料平衡计算任务状态
 */
export type MaterialBalanceJobStatus =
  | "pending"
  | "running"
  | "success"
  | "failed"
  | "cancelled"

/**
 * 物料平衡计算结果摘要
 */
export type MaterialBalanceResultSummary = {
  /**
   * 计算任务ID
   */
  job_id: string
  /**
   * 计算状态
   */
  status: MaterialBalanceJobStatus
  /**
   * 总模拟时间 (小时)
   */
  total_time?: number | null
  /**
   * 总步数
   */
  total_steps: number
  /**
   * 计算耗时 (秒)
   */
  calculation_time_seconds: number
  /**
   * 收敛状态
   */
  convergence_status: string
  /**
   * 最终质量平衡误差
   */
  final_mass_balance_error?: number | null
  /**
   * 最终总体积
   */
  final_total_volume: number
  /**
   * 求解器方法
   */
  solver_method?: string | null
  /**
   * 错误信息
   */
  error_message?: string | null
}

/**
 * 时间序列数据响应
 */
export type MaterialBalanceTimeSeriesResponse = {
  /**
   * 计算任务ID
   */
  job_id: string
  /**
   * 当前页时间点数组
   */
  timestamps: Array<number>
  /**
   * 节点时间序列数据
   */
  node_data: {
    [key: string]: {
      [key: string]: Array<number>
    }
  }
  /**
   * 边时间序列数据
   */
  edge_data: {
    [key: string]: {
      [key: string]: Array<number>
    }
  }
  /**
   * 分页信息
   */
  pagination: {
    [key: string]: unknown
  }
}

/**
 * 物料平衡参数验证请求
 */
export type MaterialBalanceValidationRequest = {
  /**
   * 待验证的输入数据
   */
  input_data: MaterialBalanceInput
}

/**
 * 物料平衡参数验证响应
 */
export type MaterialBalanceValidationResponse = {
  /**
   * 是否有效
   */
  is_valid: boolean
  /**
   * 验证错误列表
   */
  errors?: Array<string>
  /**
   * 警告信息列表
   */
  warnings?: Array<string>
  /**
   * 预估内存使用 (MB)
   */
  estimated_memory_mb: number
  /**
   * 预估计算时间 (秒)
   */
  estimated_time_seconds: number
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

/**
 * 流程图节点数据
 */
export type NodeData = {
  /**
   * 节点唯一标识符
   */
  node_id: string
  /**
   * 节点类型 (inlet, outlet, default, asm1slim, asm1等)
   */
  node_type: string
  /**
   * 是否为入口节点
   */
  is_inlet?: boolean
  /**
   * 是否为出口节点
   */
  is_outlet?: boolean
  /**
   * 初始体积 (m³)，最小值为1e-6
   */
  initial_volume: number
  /**
   * 初始浓度列表 (g/m³)
   */
  initial_concentrations: Array<number>
  /**
   * 节点在流程图中的位置
   */
  position?: {
    [key: string]: number
  }
  /**
   * ASM1 Slim模型参数 [dSNOmax, dSNHmax, CNRatio, K_S, K_NO, n_g, K_NH]
   */
  asm1slim_parameters?: Array<number> | null
  /**
   * ASM1模型参数 [u_H, K_S, K_OH, K_NO, n_g, b_H, u_A, K_NH, K_OA, b_A, Y_H, Y_A, i_XB, i_XP, f_P, n_h, K_a, K_h, K_x]
   */
  asm1_parameters?: Array<number> | null
  /**
   * ASM3模型参数 [k_H, K_X, k_STO, ny_NOX, K_O2, K_NOX, K_S, K_STO, mu_H, K_NH4, K_ALK, b_HO2, b_HNOX, b_STOO2, b_STONOX, mu_A, K_ANH4, K_AO2, K_AALK, b_AO2, b_ANOX, f_SI, Y_STOO2, Y_STONOX, Y_HO2, Y_HNOX, Y_A, f_XI, i_NSI, i_NSS, i_NXI, i_NXS, i_NBM, i_SSXI, i_SSXS, i_SSBM, i_SSSTO]
   */
  asm3_parameters?: Array<number> | null
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

/**
 * ODE求解器方法
 */
export type SolverMethod = "scipy_solver" | "euler" | "rk4" | "adaptive_heun"

/**
 * 系统健康状态
 */
export type SystemHealth = {
  /**
   * 系统状态
   */
  status: string
  /**
   * CPU使用率
   */
  cpu_usage: number
  /**
   * 内存使用率
   */
  memory_usage: number
  /**
   * 磁盘使用率
   */
  disk_usage: number
  /**
   * 活跃任务数
   */
  active_tasks: number
  /**
   * 队列大小
   */
  queue_size: number
}

/**
 * 任务进度响应
 */
export type TaskProgressResponse = {
  /**
   * 任务ID
   */
  task_id: string
  /**
   * 任务状态
   */
  status: AnalysisTaskStatus
  /**
   * 进度信息
   */
  progress: AnalysisProgress
  /**
   * 预计完成时间
   */
  estimated_completion: string | null
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  /**
   * 用户类型级别
   */
  user_type?: UserType
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  /**
   * 用户类型级别
   */
  user_type?: UserType
  id: string
  created_at: string
  updated_at: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

/**
 * 用户类型枚举
 */
export type UserType = "basic" | "pro" | "ultra" | "enterprise"

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  /**
   * 用户类型级别
   */
  user_type?: UserType
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
  /**
   * 用户类型级别
   */
  user_type?: UserType | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type Asm1CreateCalculationJobData = {
  requestBody: MaterialBalanceInput
}

export type Asm1CreateCalculationJobResponse = ASM1JobPublic

export type Asm1CreateCalculationJobFromFlowchartData = {
  requestBody: {
    [key: string]: unknown
  }
}

export type Asm1CreateCalculationJobFromFlowchartResponse = ASM1JobPublic

export type Asm1GetCalculationResultSummaryData = {
  jobId: string
}

export type Asm1GetCalculationResultSummaryResponse =
  MaterialBalanceResultSummary

export type Asm1GetCalculationFinalValuesData = {
  jobId: string
}

export type Asm1GetCalculationFinalValuesResponse = {
  [key: string]: unknown
}

export type Asm1GetCalculationTimeseriesData = {
  /**
   * 指定边ID列表
   */
  edgeIds?: Array<string> | null
  /**
   * 结束时间 (小时)
   */
  endTime?: number | null
  jobId: string
  /**
   * 指定节点ID列表
   */
  nodeIds?: Array<string> | null
  /**
   * 页码
   */
  page?: number
  /**
   * 每页数据量
   */
  pageSize?: number
  /**
   * 开始时间 (小时)
   */
  startTime?: number | null
}

export type Asm1GetCalculationTimeseriesResponse =
  MaterialBalanceTimeSeriesResponse

export type Asm1GetCalculationStatusData = {
  jobId: string
}

export type Asm1GetCalculationStatusResponse = ASM1JobPublic

export type Asm1ValidateCalculationInputData = {
  requestBody: MaterialBalanceValidationRequest
}

export type Asm1ValidateCalculationInputResponse =
  MaterialBalanceValidationResponse

export type Asm1GetUserCalculationJobsData = {
  /**
   * 返回的记录数
   */
  limit?: number
  /**
   * 跳过的记录数
   */
  skip?: number
}

export type Asm1GetUserCalculationJobsResponse = ASM1JobsPublic

export type Asm1DeleteCalculationJobData = {
  jobId: string
}

export type Asm1DeleteCalculationJobResponse = Message

export type Asm1GetJobInputDataData = {
  jobId: string
}

export type Asm1GetJobInputDataResponse = ASM1JobInputDataResponse

export type Asm1FlowchartsReadAsm1FlowchartsData = {
  limit?: number
  skip?: number
}

export type Asm1FlowchartsReadAsm1FlowchartsResponse = ASM1FlowChartsPublic

export type Asm1FlowchartsCreateAsm1FlowchartData = {
  requestBody: ASM1FlowChartCreate
}

export type Asm1FlowchartsCreateAsm1FlowchartResponse = ASM1FlowChartPublic

export type Asm1FlowchartsReadAsm1FlowchartData = {
  id: string
}

export type Asm1FlowchartsReadAsm1FlowchartResponse = ASM1FlowChartPublic

export type Asm1FlowchartsUpdateAsm1FlowchartData = {
  id: string
  requestBody: ASM1FlowChartUpdate
}

export type Asm1FlowchartsUpdateAsm1FlowchartResponse = ASM1FlowChartPublic

export type Asm1FlowchartsDeleteAsm1FlowchartData = {
  id: string
}

export type Asm1FlowchartsDeleteAsm1FlowchartResponse = Message

export type Asm1SlimCreateCalculationJobData = {
  requestBody: MaterialBalanceInput
}

export type Asm1SlimCreateCalculationJobResponse = ASM1SlimJobPublic

export type Asm1SlimCreateCalculationJobFromFlowchartData = {
  requestBody: {
    [key: string]: unknown
  }
}

export type Asm1SlimCreateCalculationJobFromFlowchartResponse =
  ASM1SlimJobPublic

export type Asm1SlimGetCalculationResultSummaryData = {
  jobId: string
}

export type Asm1SlimGetCalculationResultSummaryResponse =
  MaterialBalanceResultSummary

export type Asm1SlimGetCalculationFinalValuesData = {
  jobId: string
}

export type Asm1SlimGetCalculationFinalValuesResponse = {
  [key: string]: unknown
}

export type Asm1SlimGetCalculationTimeseriesData = {
  /**
   * 指定边ID列表
   */
  edgeIds?: Array<string> | null
  /**
   * 结束时间 (小时)
   */
  endTime?: number | null
  jobId: string
  /**
   * 指定节点ID列表
   */
  nodeIds?: Array<string> | null
  /**
   * 页码
   */
  page?: number
  /**
   * 每页数据量
   */
  pageSize?: number
  /**
   * 开始时间 (小时)
   */
  startTime?: number | null
}

export type Asm1SlimGetCalculationTimeseriesResponse =
  MaterialBalanceTimeSeriesResponse

export type Asm1SlimGetCalculationStatusData = {
  jobId: string
}

export type Asm1SlimGetCalculationStatusResponse = ASM1SlimJobPublic

export type Asm1SlimValidateCalculationInputData = {
  requestBody: MaterialBalanceValidationRequest
}

export type Asm1SlimValidateCalculationInputResponse =
  MaterialBalanceValidationResponse

export type Asm1SlimGetUserCalculationJobsData = {
  /**
   * 返回的记录数
   */
  limit?: number
  /**
   * 跳过的记录数
   */
  skip?: number
}

export type Asm1SlimGetUserCalculationJobsResponse = ASM1SlimJobsPublic

export type Asm1SlimDeleteCalculationJobData = {
  jobId: string
}

export type Asm1SlimDeleteCalculationJobResponse = Message

export type Asm1SlimGetJobInputDataData = {
  jobId: string
}

export type Asm1SlimGetJobInputDataResponse = ASM1SlimJobInputDataResponse

export type Asm1SlimFlowchartsReadAsm1SlimFlowchartsData = {
  limit?: number
  skip?: number
}

export type Asm1SlimFlowchartsReadAsm1SlimFlowchartsResponse =
  ASM1SlimFlowChartsPublic

export type Asm1SlimFlowchartsCreateAsm1SlimFlowchartData = {
  requestBody: ASM1SlimFlowChartCreate
}

export type Asm1SlimFlowchartsCreateAsm1SlimFlowchartResponse =
  ASM1SlimFlowChartPublic

export type Asm1SlimFlowchartsReadAsm1SlimFlowchartData = {
  id: string
}

export type Asm1SlimFlowchartsReadAsm1SlimFlowchartResponse =
  ASM1SlimFlowChartPublic

export type Asm1SlimFlowchartsUpdateAsm1SlimFlowchartData = {
  id: string
  requestBody: ASM1SlimFlowChartUpdate
}

export type Asm1SlimFlowchartsUpdateAsm1SlimFlowchartResponse =
  ASM1SlimFlowChartPublic

export type Asm1SlimFlowchartsDeleteAsm1SlimFlowchartData = {
  id: string
}

export type Asm1SlimFlowchartsDeleteAsm1SlimFlowchartResponse = Message

export type Asm3CreateCalculationJobData = {
  requestBody: MaterialBalanceInput
}

export type Asm3CreateCalculationJobResponse = ASM3JobPublic

export type Asm3CreateCalculationJobFromFlowchartData = {
  requestBody: {
    [key: string]: unknown
  }
}

export type Asm3CreateCalculationJobFromFlowchartResponse = ASM3JobPublic

export type Asm3GetCalculationResultSummaryData = {
  jobId: string
}

export type Asm3GetCalculationResultSummaryResponse =
  MaterialBalanceResultSummary

export type Asm3GetCalculationFinalValuesData = {
  jobId: string
}

export type Asm3GetCalculationFinalValuesResponse = {
  [key: string]: unknown
}

export type Asm3GetCalculationTimeseriesData = {
  /**
   * 指定边ID列表
   */
  edgeIds?: Array<string> | null
  /**
   * 结束时间 (小时)
   */
  endTime?: number | null
  jobId: string
  /**
   * 指定节点ID列表
   */
  nodeIds?: Array<string> | null
  /**
   * 页码
   */
  page?: number
  /**
   * 每页数据量
   */
  pageSize?: number
  /**
   * 开始时间 (小时)
   */
  startTime?: number | null
}

export type Asm3GetCalculationTimeseriesResponse =
  MaterialBalanceTimeSeriesResponse

export type Asm3GetCalculationStatusData = {
  jobId: string
}

export type Asm3GetCalculationStatusResponse = ASM3JobPublic

export type Asm3ValidateCalculationInputData = {
  requestBody: MaterialBalanceValidationRequest
}

export type Asm3ValidateCalculationInputResponse =
  MaterialBalanceValidationResponse

export type Asm3GetUserCalculationJobsData = {
  /**
   * 返回的记录数
   */
  limit?: number
  /**
   * 跳过的记录数
   */
  skip?: number
}

export type Asm3GetUserCalculationJobsResponse = ASM3JobsPublic

export type Asm3DeleteCalculationJobData = {
  jobId: string
}

export type Asm3DeleteCalculationJobResponse = Message

export type Asm3GetJobInputDataData = {
  jobId: string
}

export type Asm3GetJobInputDataResponse = ASM3JobInputDataResponse

export type Asm3FlowchartsReadAsm3FlowchartsData = {
  limit?: number
  skip?: number
}

export type Asm3FlowchartsReadAsm3FlowchartsResponse = ASM3FlowChartsPublic

export type Asm3FlowchartsCreateAsm3FlowchartData = {
  requestBody: ASM3FlowChartCreate
}

export type Asm3FlowchartsCreateAsm3FlowchartResponse = ASM3FlowChartPublic

export type Asm3FlowchartsReadAsm3FlowchartData = {
  id: string
}

export type Asm3FlowchartsReadAsm3FlowchartResponse = ASM3FlowChartPublic

export type Asm3FlowchartsUpdateAsm3FlowchartData = {
  id: string
  requestBody: ASM3FlowChartUpdate
}

export type Asm3FlowchartsUpdateAsm3FlowchartResponse = ASM3FlowChartPublic

export type Asm3FlowchartsDeleteAsm3FlowchartData = {
  id: string
}

export type Asm3FlowchartsDeleteAsm3FlowchartResponse = Message

export type DataAnalysisGetUploadPolicyResponse = {
  [key: string]: unknown
}

export type DataAnalysisUploadFileData = {
  formData: Body_data_analysis_upload_file
}

export type DataAnalysisUploadFileResponse = FileUploadResponse

export type DataAnalysisGetFilesData = {
  limit?: number
  skip?: number
  status?: FileStatus | null
}

export type DataAnalysisGetFilesResponse = FilesPublic

export type DataAnalysisGetFileData = {
  fileId: string
}

export type DataAnalysisGetFileResponse = FileDetail

export type DataAnalysisDeleteFileEndpointData = {
  fileId: string
}

export type DataAnalysisDeleteFileEndpointResponse = Message

export type DataAnalysisGetFileSchemaData = {
  fileId: string
}

export type DataAnalysisGetFileSchemaResponse = FileSchema

export type DataAnalysisPreviewFileData = {
  fileId: string
  limit?: number
  order?: string | null
  skip?: number
  sortBy?: string | null
}

export type DataAnalysisPreviewFileResponse = DataPreview

export type DataAnalysisGetBasicStatsData = {
  fileId: string
}

export type DataAnalysisGetBasicStatsResponse = BasicStats

export type DataAnalysisCreateAnalysisTaskData = {
  requestBody: AnalysisTaskCreate
}

export type DataAnalysisCreateAnalysisTaskResponse = AnalysisTaskPublic

export type DataAnalysisGetAnalysisTasksData = {
  analysisType?: AnalysisType | null
  limit?: number
  skip?: number
  status?: AnalysisTaskStatus | null
  xTimezone?: string | null
}

export type DataAnalysisGetAnalysisTasksResponse = AnalysisTasksPublic

export type DataAnalysisGetAnalysisTaskData = {
  taskId: string
}

export type DataAnalysisGetAnalysisTaskResponse = AnalysisTaskDetail

export type DataAnalysisUpdateAnalysisTaskData = {
  requestBody: AnalysisTaskUpdate
  taskId: string
}

export type DataAnalysisUpdateAnalysisTaskResponse = AnalysisTaskPublic

export type DataAnalysisDeleteAnalysisTaskData = {
  taskId: string
}

export type DataAnalysisDeleteAnalysisTaskResponse = Message

export type DataAnalysisGetTaskProgressEndpointData = {
  taskId: string
}

export type DataAnalysisGetTaskProgressEndpointResponse = TaskProgressResponse

export type DataAnalysisCancelAnalysisTaskData = {
  taskId: string
}

export type DataAnalysisCancelAnalysisTaskResponse = Message

export type DataAnalysisGetTaskResultsData = {
  limit?: number
  skip?: number
  taskId: string
}

export type DataAnalysisGetTaskResultsResponse = AnalysisResultsDetail

export type DataAnalysisGetResultData = {
  resultId: string
}

export type DataAnalysisGetResultResponse = AnalysisResultPublic

export type DataAnalysisExportResultData = {
  requestBody: ExportRequest
  resultId: string
}

export type DataAnalysisExportResultResponse = ExportResponse

export type DataAnalysisDownloadExportData = {
  filename: string
}

export type DataAnalysisDownloadExportResponse = unknown

export type DataAnalysisValidateAnalysisConfigData = {
  requestBody: AnalysisValidationRequest
}

export type DataAnalysisValidateAnalysisConfigResponse =
  AnalysisValidationResponse

export type DataAnalysisGetAnalysisStatsResponse = AnalysisStats

export type DataAnalysisGetSystemHealthResponse = SystemHealth

export type DataAnalysisGetTaskStatusQuickData = {
  taskId: string
}

export type DataAnalysisGetTaskStatusQuickResponse = {
  [key: string]: unknown
}

export type DataAnalysisGetTaskResultsQuickData = {
  taskId: string
}

export type DataAnalysisGetTaskResultsQuickResponse = {
  [key: string]: unknown
}

export type DataAnalysisUploadFileAliasData = {
  formData: Body_data_analysis_upload_file_alias
}

export type DataAnalysisUploadFileAliasResponse = FileUploadResponse

export type DataAnalysisCreateAnalysisTaskAliasData = {
  requestBody: AnalysisTaskCreate
}

export type DataAnalysisCreateAnalysisTaskAliasResponse = AnalysisTaskPublic

export type FlowchartsReadFlowchartsData = {
  limit?: number
  skip?: number
}

export type FlowchartsReadFlowchartsResponse = FlowChartsPublic

export type FlowchartsCreateFlowchartData = {
  requestBody: FlowChartCreate
}

export type FlowchartsCreateFlowchartResponse = FlowChartPublic

export type FlowchartsReadFlowchartData = {
  id: string
}

export type FlowchartsReadFlowchartResponse = FlowChartPublic

export type FlowchartsUpdateFlowchartData = {
  id: string
  requestBody: FlowChartUpdate
}

export type FlowchartsUpdateFlowchartResponse = FlowChartPublic

export type FlowchartsDeleteFlowchartData = {
  id: string
}

export type FlowchartsDeleteFlowchartResponse = Message

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type MaterialBalanceCreateCalculationJobData = {
  requestBody: MaterialBalanceInput
}

export type MaterialBalanceCreateCalculationJobResponse =
  MaterialBalanceJobPublic

export type MaterialBalanceCreateCalculationJobFromFlowchartData = {
  requestBody: {
    [key: string]: unknown
  }
}

export type MaterialBalanceCreateCalculationJobFromFlowchartResponse =
  MaterialBalanceJobPublic

export type MaterialBalanceGetCalculationResultSummaryData = {
  jobId: string
}

export type MaterialBalanceGetCalculationResultSummaryResponse =
  MaterialBalanceResultSummary

export type MaterialBalanceGetCalculationFinalValuesData = {
  jobId: string
}

export type MaterialBalanceGetCalculationFinalValuesResponse = {
  [key: string]: unknown
}

export type MaterialBalanceGetCalculationTimeseriesData = {
  /**
   * 指定边ID列表
   */
  edgeIds?: Array<string> | null
  /**
   * 结束时间 (小时)
   */
  endTime?: number | null
  jobId: string
  /**
   * 指定节点ID列表
   */
  nodeIds?: Array<string> | null
  /**
   * 页码
   */
  page?: number
  /**
   * 每页数据量
   */
  pageSize?: number
  /**
   * 开始时间 (小时)
   */
  startTime?: number | null
}

export type MaterialBalanceGetCalculationTimeseriesResponse =
  MaterialBalanceTimeSeriesResponse

export type MaterialBalanceGetCalculationStatusData = {
  jobId: string
}

export type MaterialBalanceGetCalculationStatusResponse =
  MaterialBalanceJobPublic

export type MaterialBalanceValidateCalculationInputData = {
  requestBody: MaterialBalanceValidationRequest
}

export type MaterialBalanceValidateCalculationInputResponse =
  MaterialBalanceValidationResponse

export type MaterialBalanceGetUserCalculationJobsData = {
  /**
   * 返回的记录数
   */
  limit?: number
  /**
   * 跳过的记录数
   */
  skip?: number
}

export type MaterialBalanceGetUserCalculationJobsResponse =
  MaterialBalanceJobsPublic

export type MaterialBalanceDeleteCalculationJobData = {
  jobId: string
}

export type MaterialBalanceDeleteCalculationJobResponse = Message

export type MaterialBalanceGetJobInputDataData = {
  jobId: string
}

export type MaterialBalanceGetJobInputDataResponse =
  MaterialBalanceJobInputDataResponse

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type SimpleWebsocketGetTaskConnectionsData = {
  taskId: string
}

export type SimpleWebsocketGetTaskConnectionsResponse = unknown

export type SimpleWebsocketBroadcastMessageData = {
  requestBody: {
    [key: string]: unknown
  }
  taskId: string
}

export type SimpleWebsocketBroadcastMessageResponse = unknown

export type SimpleWebsocketWebsocketHealthResponse = unknown

export type StatsGetDashboardStatsResponse = {
  [key: string]: unknown
}

export type StatsGetUserStatsResponse = {
  [key: string]: unknown
}

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean

export type WebsocketGetWebsocketStatsResponse = unknown

export type WebsocketTestSendProgressData = {
  message?: string
  progress?: number
  taskId: string
}

export type WebsocketTestSendProgressResponse = unknown

export type WebsocketTestSendCompletionData = {
  requestBody?: {
    [key: string]: unknown
  }
  taskId: string
}

export type WebsocketTestSendCompletionResponse = unknown
