"""add_material_balance_job_table

Revision ID: 03c27fb117a4
Revises: ffc412b60528
Create Date: 2025-08-06 12:07:18.831333

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '03c27fb117a4'
down_revision = 'ffc412b60528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materialbalancejob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'cancelled', name='materialbalancejobstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materialbalancejob_job_id'), 'materialbalancejob', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materialbalancejob_job_id'), table_name='materialbalancejob')
    op.drop_table('materialbalancejob')
    # ### end Alembic commands ###
