"""add_file_extension_to_data_analysis_files

Revision ID: 2ffeab197973
Revises: 86f47cc30bf9
Create Date: 2025-10-23 10:18:37.285668

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2ffeab197973'
down_revision = '86f47cc30bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_analysis_files', sa.Column('file_extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_analysis_files', 'file_extension')
    # ### end Alembic commands ###
