"""add job_name field to MaterialBalanceJob

Revision ID: 39b7b383f06b
Revises: 03c27fb117a4
Create Date: 2025-08-07 23:34:21.645875

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '39b7b383f06b'
down_revision = '03c27fb117a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add nullable job_name column
    op.add_column('materialbalancejob', sa.Column('job_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Step 2: Update existing records with default job_name
    op.execute("""
        UPDATE materialbalancejob 
        SET job_name = 'unknown_' || to_char(created_at, 'YYYYMMDDHH24MI')
        WHERE job_name IS NULL
    """)
    
    # Step 3: Make job_name NOT NULL
    op.alter_column('materialbalancejob', 'job_name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materialbalancejob', 'job_name')
    # ### end Alembic commands ###
