"""add_analysis_type_and_parameters_to_dataanalysistask

Revision ID: 67ab1fac884d
Revises: 2ffeab197973
Create Date: 2025-10-24 22:02:25.315300

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '67ab1fac884d'
down_revision = '2ffeab197973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    analysistype_enum = sa.Enum('eda', 'grouping', 'quality_control', 'timeseries', 'automl', 'custom', name='analysistype')
    analysistype_enum.create(op.get_bind())
    
    op.alter_column('data_analysis_files', 'file_extension',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    
    # Add analysis_type column as nullable first
    op.add_column('data_analysis_tasks', sa.Column('analysis_type', analysistype_enum, nullable=True))
    
    # Update existing rows with default value
    op.execute("UPDATE data_analysis_tasks SET analysis_type = 'eda' WHERE analysis_type IS NULL")
    
    # Make the column NOT NULL
    op.alter_column('data_analysis_tasks', 'analysis_type', nullable=False)
    
    op.add_column('data_analysis_tasks', sa.Column('parameters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_analysis_tasks', 'parameters')
    op.drop_column('data_analysis_tasks', 'analysis_type')
    
    # Drop the enum type
    analysistype_enum = sa.Enum('eda', 'grouping', 'quality_control', 'timeseries', 'automl', 'custom', name='analysistype')
    analysistype_enum.drop(op.get_bind())
    
    op.alter_column('data_analysis_files', 'file_extension',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
