"""Add celery_task_id to DataAnalysisTask

Revision ID: 86f47cc30bf9
Revises: f3726c41da1f
Create Date: 2025-10-21 10:11:15.248048

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '86f47cc30bf9'
down_revision = 'f3726c41da1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_analysis_tasks', sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_analysis_tasks', 'celery_task_id')
    # ### end Alembic commands ###
