"""add_asm3_flowchart_and_job_tables

Revision ID: add_asm3_tables
Revises: 8f7c8a39d873
Create Date: 2025-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'add_asm3_tables'
down_revision = '8f7c8a39d873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asm3flowchart',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('flow_data', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asm3job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'success', 'failed', 'cancelled', name='materialbalancejobstatus', create_type=False), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('summary_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asm3job_job_id'), 'asm3job', ['job_id'], unique=True)
    
    # Add asm3_parameters column to nodedata table if it doesn't exist
    # First check if the table and column exist
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    
    # Check if nodedata table exists
    if 'nodedata' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('nodedata')]
        
        if 'asm3_parameters' not in columns:
            op.add_column('nodedata', sa.Column('asm3_parameters', sa.JSON(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asm3job_job_id'), table_name='asm3job')
    op.drop_table('asm3job')
    op.drop_table('asm3flowchart')
    
    # Remove asm3_parameters column from nodedata table
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('nodedata')]
    
    if 'asm3_parameters' in columns:
        op.drop_column('nodedata', 'asm3_parameters')
    
    # ### end Alembic commands ###