"""add_summary_data_field_to_job_tables

Revision ID: c32fa0f7920c
Revises: 8f7c8a39d873
Create Date: 2025-09-02 23:47:19.408860

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c32fa0f7920c'
down_revision = '8f7c8a39d873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asm1job', sa.Column('summary_data', sa.JSON(), nullable=True))
    op.add_column('asm1slimjob', sa.Column('summary_data', sa.JSON(), nullable=True))
    op.add_column('materialbalancejob', sa.Column('summary_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materialbalancejob', 'summary_data')
    op.drop_column('asm1slimjob', 'summary_data')
    op.drop_column('asm1job', 'summary_data')
    # ### end Alembic commands ###
