"""add_user_type_field

Revision ID: cf0a5a722ac0
Revises: eca5bd9e6305
Create Date: 2025-08-12 16:27:03.346872

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cf0a5a722ac0'
down_revision = 'eca5bd9e6305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    usertype_enum = sa.Enum('basic', 'pro', 'ultra', 'enterprise', name='usertype')
    usertype_enum.create(op.get_bind())
    
    # Add the column with the enum type
    op.add_column('user', sa.Column('user_type', usertype_enum, nullable=False, server_default='basic'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    # Drop the enum type
    sa.Enum(name='usertype').drop(op.get_bind())
    # ### end Alembic commands ###
