"""change datetime fields to use local time instead of UTC

Revision ID: eca5bd9e6305
Revises: 39b7b383f06b
Create Date: 2025-08-07 23:51:52.260526

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eca5bd9e6305'
down_revision = '39b7b383f06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
