// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetHealthzResponse, GetReadyzResponse, GetMetricsResponse, CreateComputeJobData, CreateComputeJobResponse, ListComputeJobsData, ListComputeJobsResponse, GetComputeJobData, GetComputeJobResponse, CancelComputeJobData, CancelComputeJobResponse, GetComputeJobResultData, GetComputeJobResultResponse, GetComputeJobEventsData, GetComputeJobEventsResponse, DownloadArtifactData, DownloadArtifactResponse, RegisterWorkerData, RegisterWorkerResponse, ClaimWorkerJobData, ClaimWorkerJobResponse, HeartbeatWorkerData, HeartbeatWorkerResponse, UploadWorkerArtifactData, UploadWorkerArtifactResponse, SucceedWorkerJobData, SucceedWorkerJobResponse, FailWorkerJobData, FailWorkerJobResponse } from './types.gen';

export class DefaultService {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getHealthz(): CancelablePromise<GetHealthzResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/healthz'
        });
    }
    
    /**
     * @returns unknown Ready
     * @throws ApiError
     */
    public static getReadyz(): CancelablePromise<GetReadyzResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/readyz'
        });
    }
    
    /**
     * @returns unknown Prometheus metrics
     * @throws ApiError
     */
    public static getMetrics(): CancelablePromise<GetMetricsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/metrics'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @param data.idempotencyKey
     * @returns JobSnapshot Duplicate idempotency key
     * @returns JobSnapshot Queued
     * @throws ApiError
     */
    public static createComputeJob(data: CreateComputeJobData): CancelablePromise<CreateComputeJobResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/compute/jobs',
            headers: {
                'Idempotency-Key': data.idempotencyKey
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Contract error',
                409: 'Contract error'
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.limit
     * @param data.cursor
     * @param data.status
     * @param data.jobType
     * @param data.createdAfter
     * @param data.createdBefore
     * @returns ListJobsResponse Jobs
     * @throws ApiError
     */
    public static listComputeJobs(data: ListComputeJobsData = {}): CancelablePromise<ListComputeJobsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/compute/jobs',
            query: {
                limit: data.limit,
                cursor: data.cursor,
                status: data.status,
                job_type: data.jobType,
                created_after: data.createdAfter,
                created_before: data.createdBefore
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.jobId
     * @returns JobSnapshot Job
     * @throws ApiError
     */
    public static getComputeJob(data: GetComputeJobData): CancelablePromise<GetComputeJobResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/compute/jobs/{job_id}',
            path: {
                job_id: data.jobId
            },
            errors: {
                404: 'Contract error'
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.jobId
     * @returns JobSnapshot Cancelled
     * @throws ApiError
     */
    public static cancelComputeJob(data: CancelComputeJobData): CancelablePromise<CancelComputeJobResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/compute/jobs/{job_id}/cancel',
            path: {
                job_id: data.jobId
            },
            errors: {
                409: 'Contract error'
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.jobId
     * @returns unknown Result
     * @throws ApiError
     */
    public static getComputeJobResult(data: GetComputeJobResultData): CancelablePromise<GetComputeJobResultResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/compute/jobs/{job_id}/result',
            path: {
                job_id: data.jobId
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.jobId
     * @returns unknown Events
     * @throws ApiError
     */
    public static getComputeJobEvents(data: GetComputeJobEventsData): CancelablePromise<GetComputeJobEventsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/compute/jobs/{job_id}/events',
            path: {
                job_id: data.jobId
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.artifactId
     * @returns binary Artifact bytes
     * @throws ApiError
     */
    public static downloadArtifact(data: DownloadArtifactData): CancelablePromise<DownloadArtifactResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/artifacts/{artifact_id}',
            path: {
                artifact_id: data.artifactId
            },
            errors: {
                404: 'Contract error'
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns WorkerRecord Worker
     * @throws ApiError
     */
    public static registerWorker(data: RegisterWorkerData): CancelablePromise<RegisterWorkerResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/workers/register',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.workerId
     * @returns ClaimResponse Claim
     * @throws ApiError
     */
    public static claimWorkerJob(data: ClaimWorkerJobData): CancelablePromise<ClaimWorkerJobResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/workers/{worker_id}/claim',
            path: {
                worker_id: data.workerId
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.workerId
     * @param data.requestBody
     * @returns HeartbeatResponse Heartbeat
     * @throws ApiError
     */
    public static heartbeatWorker(data: HeartbeatWorkerData): CancelablePromise<HeartbeatWorkerResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/workers/{worker_id}/heartbeat',
            path: {
                worker_id: data.workerId
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.workerId
     * @param data.jobId
     * @param data.formData
     * @returns ArtifactRecord Artifact
     * @throws ApiError
     */
    public static uploadWorkerArtifact(data: UploadWorkerArtifactData): CancelablePromise<UploadWorkerArtifactResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/workers/{worker_id}/jobs/{job_id}/artifact',
            path: {
                worker_id: data.workerId,
                job_id: data.jobId
            },
            formData: data.formData,
            mediaType: 'multipart/form-data'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.workerId
     * @param data.jobId
     * @param data.requestBody
     * @returns JobSnapshot Completed
     * @throws ApiError
     */
    public static succeedWorkerJob(data: SucceedWorkerJobData): CancelablePromise<SucceedWorkerJobResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/workers/{worker_id}/jobs/{job_id}/succeed',
            path: {
                worker_id: data.workerId,
                job_id: data.jobId
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.workerId
     * @param data.jobId
     * @param data.requestBody
     * @returns JobSnapshot Failed
     * @throws ApiError
     */
    public static failWorkerJob(data: FailWorkerJobData): CancelablePromise<FailWorkerJobResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/workers/{worker_id}/jobs/{job_id}/fail',
            path: {
                worker_id: data.workerId,
                job_id: data.jobId
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}