// This file is auto-generated by @hey-api/openapi-ts

export type ArtifactRecord = {
    artifact_id: string;
    job_id: string;
    object_key: string;
    checksum: string;
    content_type?: string;
    [key: string]: unknown | string;
};

export type ClaimResponse = {
    [key: string]: unknown;
};

export type ComputeJob = {
    [key: string]: unknown;
};

export type ContractError = {
    schema_version: 'contract_error.v1';
    error_code: string;
    message: string;
    retryable: boolean;
    details?: {
        [key: string]: unknown;
    };
};

export type schema_version = 'contract_error.v1';

export type EventRecord = {
    [key: string]: unknown;
};

export type HeartbeatRequest = {
    job_id: string;
};

export type HeartbeatResponse = {
    [key: string]: unknown;
};

export type JobRecord = {
    job_id: string;
    status: string;
    job_type: string;
    payload_hash?: string;
    result_hash?: string;
    attempt?: number;
    cancel_requested?: boolean;
    [key: string]: unknown | string | number | boolean;
};

export type JobSnapshot = {
    job: JobRecord;
    artifacts: Array<ArtifactRecord>;
    event_count: number;
};

export type ListJobsResponse = {
    items: Array<JobSnapshot>;
    next_cursor?: string;
    total_estimate: number;
};

export type ParameterJobID = string;

export type ParameterWorkerID = string;

export type WorkerRecord = {
    [key: string]: unknown;
};

export type WorkerRegisterRequest = {
    worker_id?: string;
    capabilities?: Array<(string)>;
    supported_contract_versions?: Array<(string)>;
    runtime_version?: string;
};

export type GetHealthzResponse = (unknown);

export type GetReadyzResponse = (unknown);

export type GetMetricsResponse = (unknown);

export type CreateComputeJobData = {
    idempotencyKey?: string;
    requestBody: ComputeJob;
};

export type CreateComputeJobResponse = (JobSnapshot);

export type ListComputeJobsData = {
    createdAfter?: string;
    createdBefore?: string;
    cursor?: string;
    jobType?: string;
    limit?: number;
    status?: string;
};

export type ListComputeJobsResponse = (ListJobsResponse);

export type GetComputeJobData = {
    jobId: string;
};

export type GetComputeJobResponse = (JobSnapshot);

export type CancelComputeJobData = {
    jobId: string;
};

export type CancelComputeJobResponse = (JobSnapshot);

export type GetComputeJobResultData = {
    jobId: string;
};

export type GetComputeJobResultResponse = ({
    [key: string]: unknown;
});

export type GetComputeJobEventsData = {
    jobId: string;
};

export type GetComputeJobEventsResponse = ({
    items?: Array<EventRecord>;
});

export type DownloadArtifactData = {
    artifactId: string;
};

export type DownloadArtifactResponse = ((Blob | File));

export type RegisterWorkerData = {
    requestBody: WorkerRegisterRequest;
};

export type RegisterWorkerResponse = (WorkerRecord);

export type ClaimWorkerJobData = {
    workerId: string;
};

export type ClaimWorkerJobResponse = (ClaimResponse);

export type HeartbeatWorkerData = {
    requestBody: HeartbeatRequest;
    workerId: string;
};

export type HeartbeatWorkerResponse = (HeartbeatResponse);

export type UploadWorkerArtifactData = {
    formData: {
        metadata: string;
        file: (Blob | File);
    };
    jobId: string;
    workerId: string;
};

export type UploadWorkerArtifactResponse = (ArtifactRecord);

export type SucceedWorkerJobData = {
    jobId: string;
    requestBody: {
        [key: string]: unknown;
    };
    workerId: string;
};

export type SucceedWorkerJobResponse = (JobSnapshot);

export type FailWorkerJobData = {
    jobId: string;
    requestBody: {
        [key: string]: unknown;
    };
    workerId: string;
};

export type FailWorkerJobResponse = (JobSnapshot);