// This file is auto-generated by @hey-api/openapi-ts

export type ArtifactRecord = {
    artifact_id: string;
    job_id: string;
    object_key: string;
    checksum: string;
    retention_policy?: 'retain_forever' | 'ttl' | 'archive_candidate';
    retain_until?: string;
    content_type?: string;
    [key: string]: unknown | string;
};

export type retention_policy = 'retain_forever' | 'ttl' | 'archive_candidate';

export type ArtifactRetentionAction = {
    artifact_id: string;
    job_id: string;
    retention_policy: 'retain_forever' | 'ttl' | 'archive_candidate';
    retain_until?: string;
    action: 'would_delete' | 'deleted' | 'would_archive' | 'archived' | 'skipped';
    reason?: string;
    blocking_refs?: Array<(string)>;
    archive_provider?: string;
    archive_object_key?: string;
};

export type action = 'would_delete' | 'deleted' | 'would_archive' | 'archived' | 'skipped';

export type ArtifactRetentionSweepReport = {
    schema_version: 'artifact_retention_sweep.v1';
    dry_run: boolean;
    checked: number;
    deleted: number;
    archived: number;
    skipped: number;
    items: Array<ArtifactRetentionAction>;
    generated_at: string;
};

export type schema_version = 'artifact_retention_sweep.v1';

export type ArtifactRetentionSweepRequest = {
    dry_run?: boolean;
    limit?: number;
};

export type BenchmarkCasePromotionResult = {
    benchmark_case_id: string;
    case_status: string;
    latest_benchmark_run_id?: string;
    latest_benchmark_run_status?: string;
    model_run_id?: string;
    job_id?: string;
    executed_at?: string;
    parameter_hash?: string;
    parameter_hash_matches: boolean;
    evidence_ref_count: number;
    ready: boolean;
    blocking_reasons: Array<(string)>;
};

export type BenchmarkCaseRunRequest = {
    request_id?: string;
    job_id?: string;
    idempotency_key?: string;
    source_system?: string;
    requested_by?: string;
    trace_id?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type BenchmarkRun = {
    schema_version: 'benchmark_run.v1';
    benchmark_run_id: string;
    model_key: string;
    model_version: string;
    benchmark_case_id: string;
    parameter_set_id: string;
    model_run_id: string;
    job_id: string;
    status: 'passed' | 'failed' | 'error';
    metrics: {
        [key: string]: unknown;
    };
    tolerance: {
        [key: string]: unknown;
    };
    evidence_refs: Array<(string)>;
    warnings?: Array<(string)>;
    executed_at: string;
    executed_by?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type schema_version2 = 'benchmark_run.v1';

export type status = 'passed' | 'failed' | 'error';

export type BenchmarkRunRecord = {
    benchmark_run_id: string;
    schema_version: 'benchmark_run.v1';
    model_key: string;
    model_version: string;
    benchmark_case_id: string;
    parameter_set_id: string;
    model_run_id: string;
    job_id: string;
    status: 'passed' | 'failed' | 'error';
    payload_hash: string;
    payload: {
        [key: string]: unknown;
    };
    source_system: string;
    requested_by: string;
    tenant_id?: string;
    project_id?: string;
    metadata?: {
        [key: string]: unknown;
    };
    executed_at: string;
    created_at: string;
};

export type CanvasGraph = {
    [key: string]: unknown;
};

export type CanvasGraphPublishRequest = {
    process_graph?: ProcessGraph;
    parameters?: {
        [key: string]: unknown;
    };
    simulation_input_id?: string;
    register_simulation_input?: boolean;
};

export type CanvasGraphPublishResponse = {
    canvas_graph: CanvasGraphRecord;
    process_graph: ProcessGraphRecord;
    simulation_input?: SimulationInputRecord;
    validation?: {
        [key: string]: unknown;
    };
};

export type CanvasGraphRecord = {
    graph_id: string;
    scenario_id?: string;
    schema_version: 'canvas_graph.v1';
    name: string;
    version: number;
    payload_hash: string;
    payload: CanvasGraph;
    source_system: string;
    requested_by: string;
    tenant_id?: string;
    project_id?: string;
    site_id?: string;
    metadata?: {
        [key: string]: unknown;
    };
    created_at: string;
    archived_at?: string;
};

export type schema_version3 = 'canvas_graph.v1';

export type CanvasGraphSaveRequest = {
    scenario_id?: string;
    graph_id?: string;
    name?: string;
    canvas_graph: CanvasGraph;
    source_system?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type ClaimResponse = {
    [key: string]: unknown;
};

export type ComputeJob = {
    [key: string]: unknown;
};

export type ConstraintApplicationPlan = {
    schema_version: 'constraint_application_plan.v1';
    confirmation_id: string;
    draft_id: string;
    constraint_id: string;
    scope: string;
    target_ref: {
        [key: string]: unknown;
    };
    constraints: Array<{
        [key: string]: unknown;
    }>;
    application_mode: 'advisory_only';
    would_create_job: boolean;
    would_modify_target: boolean;
    production_approval_required: boolean;
    warnings: Array<(string)>;
};

export type schema_version4 = 'constraint_application_plan.v1';

export type application_mode = 'advisory_only';

export type ContextSnapshotCreateRequest = {
    context_snapshot_id?: string;
    scenario_id?: string;
    source_system?: string;
    context?: {
        [key: string]: unknown;
    };
    metadata?: {
        [key: string]: unknown;
    };
};

export type ContextSnapshotRecord = {
    context_snapshot_id: string;
    scenario_id?: string;
    schema_version: 'context_snapshot.v1';
    source_system: string;
    captured_at: string;
    payload_hash: string;
    payload: {
        [key: string]: unknown;
    };
    tenant_id?: string;
    project_id?: string;
    site_id?: string;
    metadata?: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type schema_version5 = 'context_snapshot.v1';

export type ContractError = {
    schema_version: 'contract_error.v1';
    error_code: string;
    message: string;
    retryable: boolean;
    details?: {
        [key: string]: unknown;
    };
};

export type schema_version6 = 'contract_error.v1';

export type ContractValidationIssue = {
    path: string;
    message: string;
};

export type ContractValidationResponse = {
    schema_version: 'contract_validation.v1';
    document_schema_version?: string;
    contract_schema?: string;
    valid: boolean;
    errors: Array<ContractValidationIssue>;
    warnings: Array<(string)>;
    confirmation_record?: DraftConfirmationRecord;
};

export type schema_version7 = 'contract_validation.v1';

export type DraftConfirmationRecord = {
    confirmation_id: string;
    schema_version: 'draft_confirmation.v1';
    draft_schema_version: string;
    draft_id: string;
    decision: 'approved' | 'rejected' | 'changes_requested';
    decision_reason?: string;
    confirmed_by: string;
    confirmed_at: string;
    payload_hash: string;
    payload: {
        [key: string]: unknown;
    };
    source_system: string;
    requested_by: string;
    tenant_id?: string;
    project_id?: string;
    site_id?: string;
    metadata?: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type schema_version8 = 'draft_confirmation.v1';

export type decision = 'approved' | 'rejected' | 'changes_requested';

export type EventRecord = {
    [key: string]: unknown;
};

export type EvidencePackage = {
    [key: string]: unknown;
};

export type EvidenceReferenceResolution = {
    job_id: string;
    evidence_ref: string;
    ref_type: string;
    ref_id: string;
    resolved: boolean;
    payload?: unknown;
};

export type HeartbeatRequest = {
    job_id: string;
};

export type HeartbeatResponse = {
    [key: string]: unknown;
};

export type JobRecord = {
    job_id: string;
    status: string;
    job_type: string;
    tenant_id?: string;
    project_id?: string;
    site_id?: string;
    payload_hash?: string;
    result_hash?: string;
    attempt?: number;
    cancel_requested?: boolean;
    [key: string]: unknown | string | number | boolean;
};

export type JobSnapshot = {
    job: JobRecord;
    artifacts: Array<ArtifactRecord>;
    event_count: number;
};

export type ListBenchmarkRunsResponse = {
    items: Array<BenchmarkRunRecord>;
    next_cursor?: string;
    total_estimate: number;
};

export type ListCanvasGraphsResponse = {
    items: Array<CanvasGraphRecord>;
    next_cursor?: string;
    total_estimate: number;
};

export type ListContextSnapshotsResponse = {
    items: Array<ContextSnapshotRecord>;
    next_cursor?: string;
    total_estimate: number;
};

export type ListJobsResponse = {
    items: Array<JobSnapshot>;
    next_cursor?: string;
    total_estimate: number;
};

export type ListModelCatalogSnapshotsResponse = {
    items: Array<ModelCatalogRecord>;
    next_cursor?: string;
    total_estimate: number;
};

export type ListModelRunsResponse = {
    items: Array<ModelRun>;
    next_cursor?: string;
    total_estimate: number;
};

export type ListScenariosResponse = {
    items: Array<ScenarioRecord>;
    next_cursor?: string;
    total_estimate: number;
};

export type ListUDMHybridConfigsResponse = {
    data: Array<UDMHybridConfigPublic>;
    count: number;
};

export type ListUDMModelsResponse = {
    data: Array<UDMModelPublic>;
    count: number;
};

export type ModelBenchmarkCase = {
    benchmark_case_id: string;
    display_name: string;
    description?: string;
    job_type: string;
    input_ref: {
        [key: string]: unknown;
    };
    expected_metrics: {
        [key: string]: unknown;
    };
    tolerance: {
        [key: string]: unknown;
    };
    status: 'draft' | 'validated' | 'retired';
    source?: string;
    evidence_refs?: Array<(string)>;
    metadata?: {
        [key: string]: unknown;
    };
};

export type status2 = 'draft' | 'validated' | 'retired';

export type ModelCatalog = {
    schema_version: 'model_catalog.v1';
    generated_at: string;
    models: Array<ModelCatalogModel>;
    metadata?: {
        [key: string]: unknown;
    };
};

export type schema_version9 = 'model_catalog.v1';

export type ModelCatalogModel = {
    model_key: string;
    display_name: string;
    description?: string;
    supported_job_types: Array<(string)>;
    versions: Array<ModelCatalogVersion>;
    metadata?: {
        [key: string]: unknown;
    };
};

export type ModelCatalogRecord = {
    catalog_id: string;
    schema_version: 'model_catalog.v1';
    generated_at: string;
    payload_hash: string;
    payload: ModelCatalog;
    source_system: string;
    requested_by: string;
    tenant_id?: string;
    project_id?: string;
    site_id?: string;
    metadata?: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type ModelCatalogVersion = {
    model_version: string;
    status: 'active' | 'deprecated' | 'archived';
    runtime: string;
    released_at?: string;
    parameter_templates: Array<ModelParameterTemplate>;
    benchmark_cases: Array<ModelBenchmarkCase>;
    default_parameter_set?: ModelParameterSet;
    metadata?: {
        [key: string]: unknown;
    };
};

export type status3 = 'active' | 'deprecated' | 'archived';

export type ModelParameterSet = {
    parameter_set_id: string;
    status: 'draft' | 'candidate' | 'validated' | 'approved' | 'retired';
    parameter_hash: string;
    parameters?: {
        [key: string]: unknown;
    };
    metadata?: {
        [key: string]: unknown;
    };
};

export type status4 = 'draft' | 'candidate' | 'validated' | 'approved' | 'retired';

export type ModelParameterSetPromotionPlan = {
    schema_version: 'parameter_set_promotion_plan.v1';
    model_key: string;
    model_version: string;
    parameter_set_id: string;
    parameter_hash: string;
    current_status: string;
    target_status: string;
    can_promote_to_approved: boolean;
    would_modify_catalog: boolean;
    production_approval_required: boolean;
    benchmark_cases_checked: number;
    benchmark_cases_passed: number;
    blocking_reasons: Array<(string)>;
    case_results: Array<BenchmarkCasePromotionResult>;
};

export type schema_version10 = 'parameter_set_promotion_plan.v1';

export type ModelParameterSetTransitionResponse = {
    model_key: string;
    model_version: string;
    parameter_set_id: string;
    from_status: string;
    to_status: string;
    catalog_payload_hash: string;
    created_snapshot: boolean;
    catalog: ModelCatalog;
};

export type ModelParameterTemplate = {
    parameter_key: string;
    display_name: string;
    unit?: string;
    value_type: 'number' | 'integer' | 'string' | 'boolean' | 'object' | 'array';
    required: boolean;
    default_value?: unknown;
    min_value?: number;
    max_value?: number;
    metadata?: {
        [key: string]: unknown;
    };
};

export type value_type = 'number' | 'integer' | 'string' | 'boolean' | 'object' | 'array';

export type ModelRun = {
    [key: string]: unknown;
};

export type ParameterBenchmarkCaseID = string;

export type ParameterBenchmarkRunID = string;

export type ParameterConfirmationID = string;

export type ParameterExplanationID = string;

export type ParameterJobID = string;

export type ParameterModelKey = string;

export type ParameterModelRunID = string;

export type ParameterModelVersionPath = string;

export type ParameterProcessGraphID = string;

export type ParameterSetPromotionRequest = {
    parameter_set_id?: string;
    reason?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type ParameterSetStatusUpdateRequest = {
    parameter_set_id?: string;
    from_status?: 'draft' | 'candidate' | 'validated' | 'approved' | 'retired';
    to_status: 'draft' | 'candidate' | 'validated' | 'approved' | 'retired';
    reason?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type from_status = 'draft' | 'candidate' | 'validated' | 'approved' | 'retired';

export type to_status = 'draft' | 'candidate' | 'validated' | 'approved' | 'retired';

export type ParameterSimulationInputID = string;

export type ParameterWorkerID = string;

export type ProcessGraph = {
    [key: string]: unknown;
};

export type ProcessGraphRecord = {
    process_graph_id: string;
    schema_version: 'process_graph.v1';
    version: number;
    source_canvas_graph_id: string;
    payload_hash: string;
    payload: ProcessGraph;
    source_system: string;
    requested_by: string;
    tenant_id?: string;
    project_id?: string;
    site_id?: string;
    metadata?: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type schema_version11 = 'process_graph.v1';

export type ProductionReadinessCheck = {
    check_id: string;
    status: 'passed' | 'warning' | 'failed';
    message: string;
    evidence_refs: Array<(string)>;
};

export type status5 = 'passed' | 'warning' | 'failed';

export type ProductionReadinessReport = {
    schema_version: 'production_readiness.v1';
    job_id: string;
    evidence_package_id: string;
    policy_version: string;
    readiness_status: 'ready_for_external_approval' | 'blocked';
    production_ready: boolean;
    external_approval_required: boolean;
    auto_publish_allowed: boolean;
    blocking_reasons: Array<(string)>;
    warnings: Array<(string)>;
    checks: Array<ProductionReadinessCheck>;
    risk_findings_summary: ProductionReadinessRiskSummary;
    generated_at: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type schema_version12 = 'production_readiness.v1';

export type readiness_status = 'ready_for_external_approval' | 'blocked';

export type ProductionReadinessRiskSummary = {
    total: number;
    by_severity: {
        info: number;
        low: number;
        medium: number;
        high: number;
        critical: number;
    };
    blocking: Array<(string)>;
};

export type ResultExplanationRecord = {
    schema_version: 'result_explanation_record.v1';
    explanation_id: string;
    explanation_schema_version: 'result_explanation.v1';
    job_id: string;
    status: 'submitted' | 'approved' | 'rejected' | 'published';
    created_by: string;
    payload_hash: string;
    payload: {
        [key: string]: unknown;
    };
    resolved_evidence_refs: Array<(string)>;
    source_system: string;
    requested_by: string;
    tenant_id?: string;
    project_id?: string;
    metadata?: {
        [key: string]: unknown;
    };
    submitted_at: string;
    reviewed_by?: string;
    reviewed_at?: string;
    review_decision?: 'approved' | 'rejected';
    review_reason?: string;
    published_by?: string;
    published_at?: string;
    created_at: string;
    updated_at: string;
};

export type schema_version13 = 'result_explanation_record.v1';

export type explanation_schema_version = 'result_explanation.v1';

export type status6 = 'submitted' | 'approved' | 'rejected' | 'published';

export type review_decision = 'approved' | 'rejected';

export type ResultExplanationReviewRequest = {
    decision: 'approved' | 'rejected';
    reason?: string;
};

export type decision2 = 'approved' | 'rejected';

export type ScenarioCloneRequest = {
    scenario_id?: string;
    name?: string;
    description?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type ScenarioRecord = {
    scenario_id: string;
    name: string;
    description?: string;
    model_family: string;
    status: string;
    version: number;
    current_canvas_graph_id?: string;
    current_canvas_graph_version?: number;
    published_process_graph_id?: string;
    published_process_graph_version?: number;
    current_simulation_input_id?: string;
    context_snapshot_id?: string;
    source_scenario_id?: string;
    last_job_id?: string;
    source_system: string;
    requested_by: string;
    tenant_id?: string;
    project_id?: string;
    site_id?: string;
    metadata?: {
        [key: string]: unknown;
    };
    created_at: string;
    updated_at: string;
    archived_at?: string;
};

export type ScenarioRunRequest = {
    request_id?: string;
    job_type?: string;
    idempotency_key?: string;
    trace_id?: string;
    simulation_input_id?: string;
    parameters?: {
        [key: string]: unknown;
    };
    metadata?: {
        [key: string]: unknown;
    };
};

export type ScenarioUpsertRequest = {
    scenario_id?: string;
    name?: string;
    description?: string;
    model_family?: string;
    status?: string;
    current_canvas_graph_id?: string;
    current_canvas_graph_version?: number;
    published_process_graph_id?: string;
    published_process_graph_version?: number;
    current_simulation_input_id?: string;
    context_snapshot_id?: string;
    last_job_id?: string;
    source_system?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type SimulationInput = {
    [key: string]: unknown;
};

export type SimulationInputRecord = {
    simulation_input_id: string;
    schema_version: 'simulation_input.v1';
    job_type: string;
    process_graph_id: string;
    process_graph_version: number;
    payload_hash: string;
    payload: SimulationInput;
    source_system: string;
    requested_by: string;
    tenant_id?: string;
    project_id?: string;
    site_id?: string;
    metadata?: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type schema_version14 = 'simulation_input.v1';

export type SimulationRequest = {
    schema_version: 'simulation_request.v1';
    request_id: string;
    source_system: string;
    requested_by: string;
    job_type: 'simulation.material_balance.v1' | 'simulation.asm1slim.v1' | 'simulation.asm1.v1' | 'simulation.asm3.v1' | 'simulation.udm.v1';
    input_ref: {
        process_graph_id?: string;
        process_graph_version?: number;
        simulation_input_id?: string;
        model_run_id?: string;
        simulation_input?: {
            [key: string]: unknown;
        };
        [key: string]: unknown | string | number;
    };
    external_refs?: {
        [key: string]: unknown;
    };
    metadata?: {
        [key: string]: unknown;
    };
    [key: string]: unknown | string;
};

export type schema_version15 = 'simulation_request.v1';

export type job_type = 'simulation.material_balance.v1' | 'simulation.asm1slim.v1' | 'simulation.asm1.v1' | 'simulation.asm3.v1' | 'simulation.udm.v1';

export type UDMContinuityCheckItem = {
    process_name: string;
    dimension: string;
    balance_value: number;
    status: string;
    explanation: string;
};

export type UDMHybridConfigCreateRequest = {
    name: string;
    description?: string;
    hybrid_config: {
        [key: string]: unknown;
    };
    source_system?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type UDMHybridConfigPublic = {
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
    name: string;
    description?: string;
    hybrid_config: {
        [key: string]: unknown;
    };
    parameter_hash?: string;
};

export type UDMHybridConfigUpdateRequest = {
    name?: string;
    description?: string;
    hybrid_config?: {
        [key: string]: unknown;
    };
    source_system?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type UDMModelCreateFromTemplateRequest = {
    template_key: string;
    name?: string;
    description?: string;
    source_system?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type UDMModelCreateRequest = UDMModelDefinitionDraft & {
    seed_source?: string;
    source_system?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type UDMModelDefinitionDraft = {
    name?: string;
    description?: string;
    tags?: Array<(string)>;
    components?: Array<{
        [key: string]: unknown;
    }>;
    parameters?: Array<{
        [key: string]: unknown;
    }>;
    processes?: Array<{
        [key: string]: unknown;
    }>;
    meta?: {
        [key: string]: unknown;
    };
    validation_mode?: string;
};

export type UDMModelDetailPublic = UDMModelPublic & {
    latest_version?: UDMModelVersionPublic;
    versions: Array<UDMModelVersionPublic>;
};

export type UDMModelPublic = {
    id: string;
    name: string;
    description?: string;
    tags: Array<(string)>;
    current_version: number;
    is_published: boolean;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type UDMModelUpdateRequest = {
    name?: string;
    description?: string;
    tags?: Array<(string)>;
    components?: Array<{
        [key: string]: unknown;
    }>;
    parameters?: Array<{
        [key: string]: unknown;
    }>;
    processes?: Array<{
        [key: string]: unknown;
    }>;
    meta?: {
        [key: string]: unknown;
    };
    is_published?: boolean;
    source_system?: string;
    metadata?: {
        [key: string]: unknown;
    };
};

export type UDMModelVersionPublic = {
    id: string;
    model_id: string;
    version: number;
    content_hash: string;
    parameter_hash?: string;
    components: Array<{
        [key: string]: unknown;
    }>;
    parameters: Array<{
        [key: string]: unknown;
    }>;
    processes: Array<{
        [key: string]: unknown;
    }>;
    meta?: {
        [key: string]: unknown;
    };
    validation_ok: boolean;
    validation_errors: Array<{
        [key: string]: unknown;
    }>;
    seed_source?: string;
    created_at: string;
    updated_at: string;
};

export type UDMSeedTemplateSummary = {
    key: string;
    name: string;
    description?: string;
    tags?: Array<(string)>;
    components_count?: number;
    processes_count?: number;
    parameters_count?: number;
};

export type UDMValidationIssue = {
    code: string;
    message: string;
    process?: string;
    location?: UDMValidationLocation;
};

export type UDMValidationLocation = {
    section?: string;
    process_name?: string;
    component_name?: string;
    cell_key?: string;
};

export type UDMValidationResponse = {
    ok: boolean;
    errors: Array<UDMValidationIssue>;
    warnings: Array<UDMValidationIssue>;
    extracted_parameters: Array<(string)>;
    continuity_checks: Array<UDMContinuityCheckItem>;
};

export type WorkerRecord = {
    [key: string]: unknown;
};

export type WorkerRegisterRequest = {
    worker_id?: string;
    capabilities?: Array<(string)>;
    supported_contract_versions?: Array<(string)>;
    runtime_version?: string;
};

export type GetHealthzResponse = (unknown);

export type GetReadyzResponse = (unknown);

export type GetMetricsResponse = (unknown);

export type CreateComputeJobData = {
    idempotencyKey?: string;
    requestBody: ComputeJob;
};

export type CreateComputeJobResponse = (JobSnapshot);

export type ListComputeJobsData = {
    createdAfter?: string;
    createdBefore?: string;
    cursor?: string;
    jobType?: string;
    limit?: number;
    status?: string;
};

export type ListComputeJobsResponse = (ListJobsResponse);

export type CreateSimulationCheckData = {
    requestBody: SimulationRequest;
};

export type CreateSimulationCheckResponse = (JobSnapshot);

export type RegisterProcessGraphData = {
    requestBody: ProcessGraph;
};

export type RegisterProcessGraphResponse = (ProcessGraphRecord);

export type GetProcessGraphData = {
    processGraphId: string;
    version?: number;
};

export type GetProcessGraphResponse = (ProcessGraphRecord);

export type RegisterSimulationInputData = {
    requestBody: SimulationInput;
};

export type RegisterSimulationInputResponse = (SimulationInputRecord);

export type GetSimulationInputData = {
    simulationInputId: string;
};

export type GetSimulationInputResponse = (SimulationInputRecord);

export type ListScenariosData = {
    cursor?: string;
    limit?: number;
    status?: string;
};

export type ListScenariosResponse2 = (ListScenariosResponse);

export type CreateScenarioData = {
    requestBody: ScenarioUpsertRequest;
};

export type CreateScenarioResponse = (ScenarioRecord);

export type GetScenarioData = {
    scenarioId: string;
};

export type GetScenarioResponse = (ScenarioRecord);

export type UpdateScenarioData = {
    requestBody: ScenarioUpsertRequest;
    scenarioId: string;
};

export type UpdateScenarioResponse = (ScenarioRecord);

export type ArchiveScenarioByDeleteData = {
    scenarioId: string;
};

export type ArchiveScenarioByDeleteResponse = (ScenarioRecord);

export type CloneScenarioData = {
    requestBody?: ScenarioCloneRequest;
    scenarioId: string;
};

export type CloneScenarioResponse = (ScenarioRecord);

export type ArchiveScenarioData = {
    scenarioId: string;
};

export type ArchiveScenarioResponse = (ScenarioRecord);

export type RunScenarioSimulationCheckData = {
    requestBody?: ScenarioRunRequest;
    scenarioId: string;
};

export type RunScenarioSimulationCheckResponse = (JobSnapshot);

export type ListCanvasGraphsData = {
    cursor?: string;
    limit?: number;
    scenarioId?: string;
};

export type ListCanvasGraphsResponse2 = (ListCanvasGraphsResponse);

export type SaveCanvasGraphData = {
    requestBody: CanvasGraphSaveRequest;
};

export type SaveCanvasGraphResponse = (CanvasGraphRecord);

export type GetCanvasGraphData = {
    graphId: string;
    version?: number;
};

export type GetCanvasGraphResponse = (CanvasGraphRecord);

export type UpdateCanvasGraphData = {
    graphId: string;
    requestBody: CanvasGraphSaveRequest;
};

export type UpdateCanvasGraphResponse = (CanvasGraphRecord);

export type ArchiveCanvasGraphByDeleteData = {
    graphId: string;
};

export type ArchiveCanvasGraphByDeleteResponse = ({
    [key: string]: unknown;
});

export type PublishCanvasGraphData = {
    graphId: string;
    requestBody?: CanvasGraphPublishRequest;
    version?: number;
};

export type PublishCanvasGraphResponse = (CanvasGraphPublishResponse);

export type ListContextSnapshotsData = {
    cursor?: string;
    limit?: number;
    scenarioId?: string;
};

export type ListContextSnapshotsResponse2 = (ListContextSnapshotsResponse);

export type CreateContextSnapshotData = {
    requestBody: ContextSnapshotCreateRequest;
};

export type CreateContextSnapshotResponse = (ContextSnapshotRecord);

export type GetContextSnapshotData = {
    contextSnapshotId: string;
};

export type GetContextSnapshotResponse = (ContextSnapshotRecord);

export type ListUdmModelTemplatesData = {
    excludeTags?: string;
    tags?: string;
};

export type ListUdmModelTemplatesResponse = (Array<UDMSeedTemplateSummary>);

export type ValidateUdmModelDefinitionData = {
    requestBody: UDMModelDefinitionDraft;
};

export type ValidateUdmModelDefinitionResponse = (UDMValidationResponse);

export type ListUdmModelsData = {
    limit?: number;
    q?: string;
    skip?: number;
};

export type ListUdmModelsResponse = (ListUDMModelsResponse);

export type CreateUdmModelData = {
    requestBody: UDMModelCreateRequest;
};

export type CreateUdmModelResponse = (UDMModelDetailPublic);

export type CreateUdmModelFromTemplateData = {
    requestBody: UDMModelCreateFromTemplateRequest;
};

export type CreateUdmModelFromTemplateResponse = (UDMModelDetailPublic);

export type GetUdmModelData = {
    modelId: string;
};

export type GetUdmModelResponse = (UDMModelDetailPublic);

export type UpdateUdmModelData = {
    modelId: string;
    requestBody: UDMModelUpdateRequest;
};

export type UpdateUdmModelResponse = (UDMModelDetailPublic);

export type DeleteUdmModelData = {
    modelId: string;
};

export type DeleteUdmModelResponse = ({
    [key: string]: unknown;
});

export type ListUdmHybridConfigsData = {
    limit?: number;
    skip?: number;
};

export type ListUdmHybridConfigsResponse = (ListUDMHybridConfigsResponse);

export type CreateUdmHybridConfigData = {
    requestBody: UDMHybridConfigCreateRequest;
};

export type CreateUdmHybridConfigResponse = (UDMHybridConfigPublic);

export type GetUdmHybridConfigData = {
    id: string;
};

export type GetUdmHybridConfigResponse = (UDMHybridConfigPublic);

export type UpdateUdmHybridConfigData = {
    id: string;
    requestBody: UDMHybridConfigUpdateRequest;
};

export type UpdateUdmHybridConfigResponse = (UDMHybridConfigPublic);

export type DeleteUdmHybridConfigData = {
    id: string;
};

export type DeleteUdmHybridConfigResponse = ({
    [key: string]: unknown;
});

export type GetComputeJobData = {
    jobId: string;
};

export type GetComputeJobResponse = (JobSnapshot);

export type CancelComputeJobData = {
    jobId: string;
};

export type CancelComputeJobResponse = (JobSnapshot);

export type GetComputeJobResultData = {
    jobId: string;
};

export type GetComputeJobResultResponse = ({
    [key: string]: unknown;
});

export type GetComputeJobEventsData = {
    jobId: string;
};

export type GetComputeJobEventsResponse = ({
    items?: Array<EventRecord>;
});

export type GetComputeJobEvidenceData = {
    jobId: string;
};

export type GetComputeJobEvidenceResponse = (EvidencePackage);

export type GetComputeJobProductionReadinessData = {
    jobId: string;
};

export type GetComputeJobProductionReadinessResponse = (ProductionReadinessReport);

export type ResolveEvidenceReferenceData = {
    jobId: string;
    ref: string;
};

export type ResolveEvidenceReferenceResponse = (EvidenceReferenceResolution);

export type SubmitResultExplanationData = {
    jobId: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type SubmitResultExplanationResponse = (ResultExplanationRecord);

export type GetResultExplanationData = {
    explanationId: string;
    jobId: string;
};

export type GetResultExplanationResponse = (ResultExplanationRecord);

export type ReviewResultExplanationData = {
    explanationId: string;
    jobId: string;
    requestBody: ResultExplanationReviewRequest;
};

export type ReviewResultExplanationResponse = (ResultExplanationRecord);

export type PublishResultExplanationData = {
    explanationId: string;
    jobId: string;
};

export type PublishResultExplanationResponse = (ResultExplanationRecord);

export type DownloadArtifactData = {
    artifactId: string;
};

export type DownloadArtifactResponse = ((Blob | File));

export type SweepArtifactRetentionData = {
    requestBody?: ArtifactRetentionSweepRequest;
};

export type SweepArtifactRetentionResponse = (ArtifactRetentionSweepReport);

export type ValidateContractData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type ValidateContractResponse = (ContractValidationResponse);

export type ConfirmDraftData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type ConfirmDraftResponse = (ContractValidationResponse);

export type GetDraftConfirmationData = {
    confirmationId: string;
};

export type GetDraftConfirmationResponse = (DraftConfirmationRecord);

export type GetConstraintApplicationPlanData = {
    confirmationId: string;
};

export type GetConstraintApplicationPlanResponse = (ConstraintApplicationPlan);

export type PromoteDraftConfirmationToSimulationCheckData = {
    confirmationId: string;
};

export type PromoteDraftConfirmationToSimulationCheckResponse = (JobSnapshot);

export type ListModelCatalogResponse = (ModelCatalog);

export type RegisterModelCatalogData = {
    requestBody: ModelCatalog;
};

export type RegisterModelCatalogResponse = (ModelCatalogRecord);

export type ListModelCatalogSnapshotsData = {
    catalogId?: string;
    cursor?: string;
    limit?: number;
};

export type ListModelCatalogSnapshotsResponse2 = (ListModelCatalogSnapshotsResponse);

export type GetModelCatalogModelData = {
    modelKey: string;
};

export type GetModelCatalogModelResponse = (ModelCatalogModel);

export type UpdateDefaultParameterSetStatusData = {
    modelKey: string;
    modelVersion: string;
    requestBody: ParameterSetStatusUpdateRequest;
};

export type UpdateDefaultParameterSetStatusResponse = (ModelParameterSetTransitionResponse);

export type GetDefaultParameterSetPromotionPlanData = {
    /**
     * Optional benchmark evidence job filter; required for tenant/project/site scoped tokens.
     */
    jobId?: string;
    modelKey: string;
    modelVersion: string;
};

export type GetDefaultParameterSetPromotionPlanResponse = (ModelParameterSetPromotionPlan);

export type PromoteDefaultParameterSetToApprovedData = {
    /**
     * Optional benchmark evidence job filter; required for tenant/project/site scoped tokens.
     */
    jobId?: string;
    modelKey: string;
    modelVersion: string;
    requestBody?: ParameterSetPromotionRequest;
};

export type PromoteDefaultParameterSetToApprovedResponse = (ModelParameterSetTransitionResponse);

export type ScheduleBenchmarkCaseRunData = {
    benchmarkCaseId: string;
    modelKey: string;
    modelVersion: string;
    requestBody?: BenchmarkCaseRunRequest;
};

export type ScheduleBenchmarkCaseRunResponse = (JobSnapshot);

export type ListBenchmarkRunsData = {
    benchmarkCaseId?: string;
    cursor?: string;
    jobId?: string;
    limit?: number;
    modelKey: string;
    modelVersion: string;
    parameterSetId?: string;
};

export type ListBenchmarkRunsResponse2 = (ListBenchmarkRunsResponse);

export type RecordBenchmarkRunData = {
    modelKey: string;
    modelVersion: string;
    requestBody: BenchmarkRun;
};

export type RecordBenchmarkRunResponse = (BenchmarkRunRecord);

export type GetBenchmarkRunData = {
    benchmarkRunId: string;
};

export type GetBenchmarkRunResponse = (BenchmarkRunRecord);

export type ListModelRunsData = {
    cursor?: string;
    jobId?: string;
    limit?: number;
    modelKey?: string;
    modelVersion?: string;
};

export type ListModelRunsResponse2 = (ListModelRunsResponse);

export type GetModelRunData = {
    modelRunId: string;
};

export type GetModelRunResponse = (ModelRun);

export type RegisterWorkerData = {
    requestBody: WorkerRegisterRequest;
};

export type RegisterWorkerResponse = (WorkerRecord);

export type ClaimWorkerJobData = {
    workerId: string;
};

export type ClaimWorkerJobResponse = (ClaimResponse);

export type HeartbeatWorkerData = {
    requestBody: HeartbeatRequest;
    workerId: string;
};

export type HeartbeatWorkerResponse = (HeartbeatResponse);

export type UploadWorkerArtifactData = {
    formData: {
        metadata: string;
        file: (Blob | File);
    };
    jobId: string;
    workerId: string;
};

export type UploadWorkerArtifactResponse = (ArtifactRecord);

export type SucceedWorkerJobData = {
    jobId: string;
    requestBody: {
        [key: string]: unknown;
    };
    workerId: string;
};

export type SucceedWorkerJobResponse = (JobSnapshot);

export type FailWorkerJobData = {
    jobId: string;
    requestBody: {
        [key: string]: unknown;
    };
    workerId: string;
};

export type FailWorkerJobResponse = (JobSnapshot);
