/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ShowcaseImport } from './routes/showcase'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as PosthogDemoImport } from './routes/posthog-demo'
import { Route as OpenflowImport } from './routes/openflow'
import { Route as MiddayStyleImport } from './routes/midday-style'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as UpdatesIndexImport } from './routes/updates/index'
import { Route as DocsIndexImport } from './routes/docs/index'
import { Route as CalculatorsIndexImport } from './routes/calculators/index'
import { Route as AiDeepResearchIndexImport } from './routes/ai-deep-research/index'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as UpdatesSlugImport } from './routes/updates/$slug'
import { Route as AiDeepResearchArticleIdImport } from './routes/ai-deep-research/$articleId'
import { Route as LayoutSuperDashboardImport } from './routes/_layout/super-dashboard'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutOverviewImport } from './routes/_layout/overview'
import { Route as LayoutMaterialbalanceImport } from './routes/_layout/materialbalance'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutDashboardImport } from './routes/_layout/dashboard'
import { Route as LayoutAsm3Import } from './routes/_layout/asm3'
import { Route as LayoutAsm1slimImport } from './routes/_layout/asm1slim'
import { Route as LayoutAsm1Import } from './routes/_layout/asm1'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutKnowledgeIndexImport } from './routes/_layout/knowledge/index'
import { Route as DocsSplatSlugImport } from './routes/docs/$...slug'
import { Route as LayoutKnowledgeSplatSlugImport } from './routes/_layout/knowledge/$...slug'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ShowcaseRoute = ShowcaseImport.update({
  path: '/showcase',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const PosthogDemoRoute = PosthogDemoImport.update({
  path: '/posthog-demo',
  getParentRoute: () => rootRoute,
} as any)

const OpenflowRoute = OpenflowImport.update({
  path: '/openflow',
  getParentRoute: () => rootRoute,
} as any)

const MiddayStyleRoute = MiddayStyleImport.update({
  path: '/midday-style',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UpdatesIndexRoute = UpdatesIndexImport.update({
  path: '/updates/',
  getParentRoute: () => rootRoute,
} as any)

const DocsIndexRoute = DocsIndexImport.update({
  path: '/docs/',
  getParentRoute: () => rootRoute,
} as any)

const CalculatorsIndexRoute = CalculatorsIndexImport.update({
  path: '/calculators/',
  getParentRoute: () => rootRoute,
} as any)

const AiDeepResearchIndexRoute = AiDeepResearchIndexImport.update({
  path: '/ai-deep-research/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const UpdatesSlugRoute = UpdatesSlugImport.update({
  path: '/updates/$slug',
  getParentRoute: () => rootRoute,
} as any)

const AiDeepResearchArticleIdRoute = AiDeepResearchArticleIdImport.update({
  path: '/ai-deep-research/$articleId',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSuperDashboardRoute = LayoutSuperDashboardImport.update({
  path: '/super-dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOverviewRoute = LayoutOverviewImport.update({
  path: '/overview',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMaterialbalanceRoute = LayoutMaterialbalanceImport.update({
  path: '/materialbalance',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRoute = LayoutDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAsm3Route = LayoutAsm3Import.update({
  path: '/asm3',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAsm1slimRoute = LayoutAsm1slimImport.update({
  path: '/asm1slim',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAsm1Route = LayoutAsm1Import.update({
  path: '/asm1',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutKnowledgeIndexRoute = LayoutKnowledgeIndexImport.update({
  path: '/knowledge/',
  getParentRoute: () => LayoutRoute,
} as any)

const DocsSplatSlugRoute = DocsSplatSlugImport.update({
  path: '/docs/$/slug',
  getParentRoute: () => rootRoute,
} as any)

const LayoutKnowledgeSplatSlugRoute = LayoutKnowledgeSplatSlugImport.update({
  path: '/knowledge/$/slug',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/midday-style': {
      preLoaderRoute: typeof MiddayStyleImport
      parentRoute: typeof rootRoute
    }
    '/openflow': {
      preLoaderRoute: typeof OpenflowImport
      parentRoute: typeof rootRoute
    }
    '/posthog-demo': {
      preLoaderRoute: typeof PosthogDemoImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/showcase': {
      preLoaderRoute: typeof ShowcaseImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/asm1': {
      preLoaderRoute: typeof LayoutAsm1Import
      parentRoute: typeof LayoutImport
    }
    '/_layout/asm1slim': {
      preLoaderRoute: typeof LayoutAsm1slimImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/asm3': {
      preLoaderRoute: typeof LayoutAsm3Import
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard': {
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/materialbalance': {
      preLoaderRoute: typeof LayoutMaterialbalanceImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/overview': {
      preLoaderRoute: typeof LayoutOverviewImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/super-dashboard': {
      preLoaderRoute: typeof LayoutSuperDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/ai-deep-research/$articleId': {
      preLoaderRoute: typeof AiDeepResearchArticleIdImport
      parentRoute: typeof rootRoute
    }
    '/updates/$slug': {
      preLoaderRoute: typeof UpdatesSlugImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/ai-deep-research/': {
      preLoaderRoute: typeof AiDeepResearchIndexImport
      parentRoute: typeof rootRoute
    }
    '/calculators/': {
      preLoaderRoute: typeof CalculatorsIndexImport
      parentRoute: typeof rootRoute
    }
    '/docs/': {
      preLoaderRoute: typeof DocsIndexImport
      parentRoute: typeof rootRoute
    }
    '/updates/': {
      preLoaderRoute: typeof UpdatesIndexImport
      parentRoute: typeof rootRoute
    }
    '/docs/$/slug': {
      preLoaderRoute: typeof DocsSplatSlugImport
      parentRoute: typeof rootRoute
    }
    '/_layout/knowledge/': {
      preLoaderRoute: typeof LayoutKnowledgeIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/knowledge/$/slug': {
      preLoaderRoute: typeof LayoutKnowledgeSplatSlugImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutAsm1Route,
    LayoutAsm1slimRoute,
    LayoutAsm3Route,
    LayoutDashboardRoute,
    LayoutItemsRoute,
    LayoutMaterialbalanceRoute,
    LayoutOverviewRoute,
    LayoutSettingsRoute,
    LayoutSuperDashboardRoute,
    LayoutIndexRoute,
    LayoutKnowledgeIndexRoute,
    LayoutKnowledgeSplatSlugRoute,
  ]),
  LoginRoute,
  MiddayStyleRoute,
  OpenflowRoute,
  PosthogDemoRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  ShowcaseRoute,
  SignupRoute,
  AiDeepResearchArticleIdRoute,
  UpdatesSlugRoute,
  AiDeepResearchIndexRoute,
  CalculatorsIndexRoute,
  DocsIndexRoute,
  UpdatesIndexRoute,
  DocsSplatSlugRoute,
])

/* prettier-ignore-end */
